package kraken

import "github.com/ccxt/ccxt/go/v4/ccxt"

type KrakenfuturesWs struct {
   *krakenfuturesWs
   Core *krakenfuturesWs
}

func NewKrakenfuturesWs(userConfig map[string]interface{}) KrakenfuturesWs {
   p := &krakenfuturesWs{}
   p.Init(userConfig)
   return KrakenfuturesWs{
       krakenfuturesWs: p,
       Core:  p,
   }
}

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


func (this *KrakenfuturesWs) WatchOrderBookForSymbols(symbols []string, options ...ccxt.WatchOrderBookForSymbolsOptions) (ccxt.IOrderBook, error) {

    opts := ccxt.WatchOrderBookForSymbolsOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var limit interface{} = nil
    if opts.Limit != nil {
        limit = *opts.Limit
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.WatchOrderBookForSymbols(symbols, limit, params)
    if ccxt.IsError(res) {
        return ccxt.IOrderBook{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewIOrderBook(res), nil
}
func (this *KrakenfuturesWs) WatchTicker(symbol string, options ...ccxt.WatchTickerOptions) (ccxt.Ticker, error) {

    opts := ccxt.WatchTickerOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.WatchTicker(symbol, params)
    if ccxt.IsError(res) {
        return ccxt.Ticker{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewTicker(res), nil
}
func (this *KrakenfuturesWs) WatchTickers(options ...ccxt.WatchTickersOptions) (ccxt.Tickers, error) {

    opts := ccxt.WatchTickersOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var symbols interface{} = nil
    if opts.Symbols != nil {
        symbols = *opts.Symbols
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.WatchTickers(symbols, params)
    if ccxt.IsError(res) {
        return ccxt.Tickers{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewTickers(res), nil
}
func (this *KrakenfuturesWs) WatchBidsAsks(options ...ccxt.WatchBidsAsksOptions) (ccxt.Tickers, error) {

    opts := ccxt.WatchBidsAsksOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var symbols interface{} = nil
    if opts.Symbols != nil {
        symbols = *opts.Symbols
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.WatchBidsAsks(symbols, params)
    if ccxt.IsError(res) {
        return ccxt.Tickers{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewTickers(res), nil
}
func (this *KrakenfuturesWs) WatchTrades(symbol string, options ...ccxt.WatchTradesOptions) ([]ccxt.Trade, error) {

    opts := ccxt.WatchTradesOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var since interface{} = nil
    if opts.Since != nil {
        since = *opts.Since
    }

    var limit interface{} = nil
    if opts.Limit != nil {
        limit = *opts.Limit
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.WatchTrades(symbol, since, limit, params)
    if ccxt.IsError(res) {
        return nil, ccxt.CreateReturnError(res)
    }
    return ccxt.NewTradeArray(res), nil
}
func (this *KrakenfuturesWs) WatchTradesForSymbols(symbols []string, options ...ccxt.WatchTradesForSymbolsOptions) ([]ccxt.Trade, error) {

    opts := ccxt.WatchTradesForSymbolsOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var since interface{} = nil
    if opts.Since != nil {
        since = *opts.Since
    }

    var limit interface{} = nil
    if opts.Limit != nil {
        limit = *opts.Limit
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.WatchTradesForSymbols(symbols, since, limit, params)
    if ccxt.IsError(res) {
        return nil, ccxt.CreateReturnError(res)
    }
    return ccxt.NewTradeArray(res), nil
}
func (this *KrakenfuturesWs) WatchOrderBook(symbol string, options ...ccxt.WatchOrderBookOptions) (ccxt.IOrderBook, error) {

    opts := ccxt.WatchOrderBookOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var limit interface{} = nil
    if opts.Limit != nil {
        limit = *opts.Limit
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.WatchOrderBook(symbol, limit, params)
    if ccxt.IsError(res) {
        return ccxt.IOrderBook{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewIOrderBook(res), nil
}
func (this *KrakenfuturesWs) WatchPositions(options ...ccxt.WatchPositionsOptions) ([]ccxt.Position, error) {

    opts := ccxt.WatchPositionsOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var symbols interface{} = nil
    if opts.Symbols != nil {
        symbols = *opts.Symbols
    }

    var since interface{} = nil
    if opts.Since != nil {
        since = *opts.Since
    }

    var limit interface{} = nil
    if opts.Limit != nil {
        limit = *opts.Limit
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.WatchPositions(symbols, since, limit, params)
    if ccxt.IsError(res) {
        return nil, ccxt.CreateReturnError(res)
    }
    return ccxt.NewPositionArray(res), nil
}
func (this *KrakenfuturesWs) WatchOrders(options ...ccxt.WatchOrdersOptions) ([]ccxt.Order, error) {

    opts := ccxt.WatchOrdersOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var symbol interface{} = nil
    if opts.Symbol != nil {
        symbol = *opts.Symbol
    }

    var since interface{} = nil
    if opts.Since != nil {
        since = *opts.Since
    }

    var limit interface{} = nil
    if opts.Limit != nil {
        limit = *opts.Limit
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.WatchOrders(symbol, since, limit, params)
    if ccxt.IsError(res) {
        return nil, ccxt.CreateReturnError(res)
    }
    return ccxt.NewOrderArray(res), nil
}
func (this *KrakenfuturesWs) WatchMyTrades(options ...ccxt.WatchMyTradesOptions) ([]ccxt.Trade, error) {

    opts := ccxt.WatchMyTradesOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var symbol interface{} = nil
    if opts.Symbol != nil {
        symbol = *opts.Symbol
    }

    var since interface{} = nil
    if opts.Since != nil {
        since = *opts.Since
    }

    var limit interface{} = nil
    if opts.Limit != nil {
        limit = *opts.Limit
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.WatchMyTrades(symbol, since, limit, params)
    if ccxt.IsError(res) {
        return nil, ccxt.CreateReturnError(res)
    }
    return ccxt.NewTradeArray(res), nil
}
func (this *KrakenfuturesWs) WatchBalance(params ...interface{}) (ccxt.Balances, error) {
    res := <- this.Core.WatchBalance(params...)
    if ccxt.IsError(res) {
        return ccxt.Balances{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewBalances(res), nil
}
func (this *KrakenfuturesWs) WatchMultiHelper(unifiedName string, channelName string, options ...ccxt.WatchMultiHelperOptions) (map[string]interface{}, error) {

    opts := ccxt.WatchMultiHelperOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var symbols interface{} = nil
    if opts.Symbols != nil {
        symbols = *opts.Symbols
    }

    var subscriptionArgs interface{} = nil
    if opts.SubscriptionArgs != nil {
        subscriptionArgs = *opts.SubscriptionArgs
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.WatchMultiHelper(unifiedName, channelName, symbols, subscriptionArgs, params)
    if ccxt.IsError(res) {
        return map[string]interface{}{}, ccxt.CreateReturnError(res)
    }
    return res.(map[string]interface{}), nil
}