// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package bitopro

import ccxt "github.com/ccxt/ccxt/go/v4/ccxt"

func (this *bitopro) PublicGetOrderBookPair (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetOrderBookPair", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitopro) PublicGetTickers (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetTickers", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitopro) PublicGetTickersPair (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetTickersPair", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitopro) PublicGetTradesPair (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetTradesPair", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitopro) PublicGetProvisioningCurrencies (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetProvisioningCurrencies", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitopro) PublicGetProvisioningTradingPairs (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetProvisioningTradingPairs", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitopro) PublicGetProvisioningLimitationsAndFees (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetProvisioningLimitationsAndFees", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitopro) PublicGetTradingHistoryPair (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetTradingHistoryPair", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitopro) PublicGetPriceOtcCurrency (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetPriceOtcCurrency", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitopro) PrivateGetAccountsBalance (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetAccountsBalance", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitopro) PrivateGetOrdersHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetOrdersHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitopro) PrivateGetOrdersAllPair (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetOrdersAllPair", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitopro) PrivateGetOrdersTradesPair (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetOrdersTradesPair", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitopro) PrivateGetOrdersPairOrderId (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetOrdersPairOrderId", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitopro) PrivateGetWalletWithdrawCurrencySerial (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetWalletWithdrawCurrencySerial", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitopro) PrivateGetWalletWithdrawCurrencyIdId (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetWalletWithdrawCurrencyIdId", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitopro) PrivateGetWalletDepositHistoryCurrency (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetWalletDepositHistoryCurrency", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitopro) PrivateGetWalletWithdrawHistoryCurrency (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetWalletWithdrawHistoryCurrency", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitopro) PrivateGetOrdersOpen (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetOrdersOpen", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitopro) PrivatePostOrdersPair (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostOrdersPair", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitopro) PrivatePostOrdersBatch (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostOrdersBatch", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitopro) PrivatePostWalletWithdrawCurrency (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostWalletWithdrawCurrency", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitopro) PrivatePutOrders (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePutOrders", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitopro) PrivateDeleteOrdersPairId (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateDeleteOrdersPairId", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitopro) PrivateDeleteOrdersAll (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateDeleteOrdersAll", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitopro) PrivateDeleteOrdersPair (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateDeleteOrdersPair", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}
