// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package okcoin

import ccxt "github.com/ccxt/ccxt/go/v4/ccxt"

func (this *okcoin) PublicGetMarketTickers (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetMarketTickers", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PublicGetMarketTicker (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetMarketTicker", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PublicGetMarketBooks (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetMarketBooks", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PublicGetMarketCandles (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetMarketCandles", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PublicGetMarketHistoryCandles (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetMarketHistoryCandles", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PublicGetMarketTrades (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetMarketTrades", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PublicGetMarketHistoryTrades (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetMarketHistoryTrades", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PublicGetMarketPlatform24Volume (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetMarketPlatform24Volume", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PublicGetMarketOpenOracle (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetMarketOpenOracle", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PublicGetMarketExchangeRate (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetMarketExchangeRate", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PublicGetPublicInstruments (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetPublicInstruments", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PublicGetPublicTime (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetPublicTime", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetTradeOrder (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetTradeOrder", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetTradeOrdersPending (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetTradeOrdersPending", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetTradeOrdersHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetTradeOrdersHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetTradeOrdersHistoryArchive (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetTradeOrdersHistoryArchive", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetTradeFills (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetTradeFills", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetTradeFillsHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetTradeFillsHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetTradeFillsArchive (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetTradeFillsArchive", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetTradeOrderAlgo (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetTradeOrderAlgo", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetTradeOrdersAlgoPending (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetTradeOrdersAlgoPending", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetTradeOrdersAlgoHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetTradeOrdersAlgoHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetOtcRfqTrade (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetOtcRfqTrade", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetOtcRfqHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetOtcRfqHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetAccountBalance (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetAccountBalance", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetAccountBills (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetAccountBills", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetAccountBillsArchive (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetAccountBillsArchive", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetAccountConfig (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetAccountConfig", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetAccountMaxSize (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetAccountMaxSize", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetAccountMaxAvailSize (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetAccountMaxAvailSize", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetAccountTradeFee (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetAccountTradeFee", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetAccountMaxWithdrawal (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetAccountMaxWithdrawal", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetAssetCurrencies (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetAssetCurrencies", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetAssetBalances (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetAssetBalances", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetAssetAssetValuation (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetAssetAssetValuation", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetAssetTransferState (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetAssetTransferState", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetAssetBills (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetAssetBills", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetAssetDepositLightning (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetAssetDepositLightning", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetAssetDepositAddress (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetAssetDepositAddress", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetAssetDepositHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetAssetDepositHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetAssetWithdrawalHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetAssetWithdrawalHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetAssetDepositWithdrawStatus (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetAssetDepositWithdrawStatus", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetFiatDepositHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetFiatDepositHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetFiatWithdrawHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetFiatWithdrawHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetFiatChannel (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetFiatChannel", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetUsersSubaccountList (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetUsersSubaccountList", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetUsersSubaccountApiKey (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetUsersSubaccountApiKey", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetAccountSubaccountBalances (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetAccountSubaccountBalances", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetAssetSubaccountBalances (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetAssetSubaccountBalances", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivateGetAssetSubaccountBills (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetAssetSubaccountBills", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivatePostTradeOrder (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostTradeOrder", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivatePostTradeBatchOrders (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostTradeBatchOrders", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivatePostTradeCancelOrder (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostTradeCancelOrder", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivatePostTradeCancelBatchOrders (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostTradeCancelBatchOrders", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivatePostTradeAmendOrder (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostTradeAmendOrder", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivatePostTradeAmendBatchOrders (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostTradeAmendBatchOrders", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivatePostTradeOrderAlgo (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostTradeOrderAlgo", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivatePostTradeCancelAlgos (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostTradeCancelAlgos", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivatePostTradeCancelAdvanceAlgos (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostTradeCancelAdvanceAlgos", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivatePostOtcRfqQuote (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostOtcRfqQuote", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivatePostOtcRfqTrade (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostOtcRfqTrade", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivatePostAssetTransfer (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostAssetTransfer", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivatePostAssetWithdrawal (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostAssetWithdrawal", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivatePostAssetWithdrawalLightning (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostAssetWithdrawalLightning", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivatePostAssetWithdrawalCancel (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostAssetWithdrawalCancel", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivatePostFiatDeposit (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostFiatDeposit", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivatePostFiatCancelDeposit (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostFiatCancelDeposit", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivatePostFiatWithdrawal (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostFiatWithdrawal", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivatePostFiatCancelWithdrawal (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostFiatCancelWithdrawal", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *okcoin) PrivatePostAssetSubaccountTransfer (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostAssetSubaccountTransfer", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}
