package btcbox
import "github.com/ccxt/ccxt/go/v4/ccxt"

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

type btcbox struct {
    ccxt.Exchange

}

func NewBtcboxCore() btcbox {
   p := btcbox{}
   ccxt.SetDefaults(&p)
   return p
}

func  (this *btcbox) Describe() interface{}  {
    return this.DeepExtend(this.Exchange.Describe(), map[string]interface{} {
        "id": "btcbox",
        "name": "BtcBox",
        "countries": []interface{}{"JP"},
        "rateLimit": 1000,
        "version": "v1",
        "pro": false,
        "has": map[string]interface{} {
            "CORS": nil,
            "spot": true,
            "margin": false,
            "swap": false,
            "future": false,
            "option": false,
            "addMargin": false,
            "borrowCrossMargin": false,
            "borrowIsolatedMargin": false,
            "borrowMargin": false,
            "cancelOrder": true,
            "closeAllPositions": false,
            "closePosition": false,
            "createOrder": true,
            "createOrderWithTakeProfitAndStopLoss": false,
            "createOrderWithTakeProfitAndStopLossWs": false,
            "createPostOnlyOrder": false,
            "createReduceOnlyOrder": false,
            "fetchBalance": true,
            "fetchBorrowInterest": false,
            "fetchBorrowRate": false,
            "fetchBorrowRateHistories": false,
            "fetchBorrowRateHistory": false,
            "fetchBorrowRates": false,
            "fetchBorrowRatesPerSymbol": false,
            "fetchCrossBorrowRate": false,
            "fetchCrossBorrowRates": false,
            "fetchFundingHistory": false,
            "fetchFundingInterval": false,
            "fetchFundingIntervals": false,
            "fetchFundingRate": false,
            "fetchFundingRateHistory": false,
            "fetchFundingRates": false,
            "fetchGreeks": false,
            "fetchIndexOHLCV": false,
            "fetchIsolatedBorrowRate": false,
            "fetchIsolatedBorrowRates": false,
            "fetchIsolatedPositions": false,
            "fetchLeverage": false,
            "fetchLeverages": false,
            "fetchLeverageTiers": false,
            "fetchLiquidations": false,
            "fetchLongShortRatio": false,
            "fetchLongShortRatioHistory": false,
            "fetchMarginAdjustmentHistory": false,
            "fetchMarginMode": false,
            "fetchMarginModes": false,
            "fetchMarketLeverageTiers": false,
            "fetchMarkOHLCV": false,
            "fetchMarkPrices": false,
            "fetchMyLiquidations": false,
            "fetchMySettlementHistory": false,
            "fetchOpenInterest": false,
            "fetchOpenInterestHistory": false,
            "fetchOpenInterests": false,
            "fetchOpenOrders": true,
            "fetchOption": false,
            "fetchOptionChain": false,
            "fetchOrder": true,
            "fetchOrderBook": true,
            "fetchOrders": true,
            "fetchPosition": false,
            "fetchPositionHistory": false,
            "fetchPositionMode": false,
            "fetchPositions": false,
            "fetchPositionsForSymbol": false,
            "fetchPositionsHistory": false,
            "fetchPositionsRisk": false,
            "fetchPremiumIndexOHLCV": false,
            "fetchSettlementHistory": false,
            "fetchTicker": true,
            "fetchTickers": true,
            "fetchTrades": true,
            "fetchTransfer": false,
            "fetchTransfers": false,
            "fetchVolatilityHistory": false,
            "fetchWithdrawal": false,
            "fetchWithdrawals": false,
            "reduceMargin": false,
            "repayCrossMargin": false,
            "repayIsolatedMargin": false,
            "repayMargin": false,
            "setLeverage": false,
            "setMargin": false,
            "setMarginMode": false,
            "setPositionMode": false,
            "transfer": false,
            "withdraw": false,
            "ws": false,
        },
        "urls": map[string]interface{} {
            "logo": "https://github.com/user-attachments/assets/1e2cb499-8d0f-4f8f-9464-3c015cfbc76b",
            "api": map[string]interface{} {
                "rest": "https://www.btcbox.co.jp/api",
            },
            "www": "https://www.btcbox.co.jp/",
            "doc": "https://blog.btcbox.jp/en/archives/8762",
            "fees": "https://support.btcbox.co.jp/hc/en-us/articles/360001235694-Fees-introduction",
        },
        "api": map[string]interface{} {
            "public": map[string]interface{} {
                "get": []interface{}{"depth", "orders", "ticker", "tickers"},
            },
            "private": map[string]interface{} {
                "post": []interface{}{"balance", "trade_add", "trade_cancel", "trade_list", "trade_view", "wallet"},
            },
            "webApi": map[string]interface{} {
                "get": []interface{}{"ajax/coin/coinInfo"},
            },
        },
        "options": map[string]interface{} {
            "fetchMarkets": map[string]interface{} {
                "webApiEnable": true,
                "webApiRetries": 3,
            },
            "amountPrecision": "0.0001",
        },
        "features": map[string]interface{} {
            "spot": map[string]interface{} {
                "sandbox": false,
                "createOrder": map[string]interface{} {
                    "marginMode": false,
                    "triggerPrice": false,
                    "triggerPriceType": nil,
                    "triggerDirection": false,
                    "stopLossPrice": false,
                    "takeProfitPrice": false,
                    "attachedStopLossTakeProfit": nil,
                    "timeInForce": map[string]interface{} {
                        "IOC": false,
                        "FOK": false,
                        "PO": false,
                        "GTD": false,
                    },
                    "hedged": false,
                    "leverage": false,
                    "marketBuyRequiresPrice": false,
                    "marketBuyByCost": false,
                    "selfTradePrevention": false,
                    "trailing": false,
                    "iceberg": false,
                },
                "createOrders": nil,
                "fetchMyTrades": nil,
                "fetchOrder": map[string]interface{} {
                    "marginMode": false,
                    "trigger": false,
                    "trailing": false,
                    "symbolRequired": true,
                },
                "fetchOpenOrders": map[string]interface{} {
                    "marginMode": false,
                    "limit": 100,
                    "trigger": false,
                    "trailing": false,
                    "symbolRequired": true,
                },
                "fetchOrders": map[string]interface{} {
                    "marginMode": false,
                    "limit": 100,
                    "daysBack": nil,
                    "untilDays": nil,
                    "trigger": false,
                    "trailing": false,
                    "symbolRequired": true,
                },
                "fetchClosedOrders": nil,
                "fetchOHLCV": nil,
            },
            "swap": map[string]interface{} {
                "linear": nil,
                "inverse": nil,
            },
            "future": map[string]interface{} {
                "linear": nil,
                "inverse": nil,
            },
        },
        "precisionMode": ccxt.TICK_SIZE,
        "exceptions": map[string]interface{} {
            "104": ccxt.AuthenticationError,
            "105": ccxt.PermissionDenied,
            "106": ccxt.InvalidNonce,
            "107": ccxt.InvalidOrder,
            "200": ccxt.InsufficientFunds,
            "201": ccxt.InvalidOrder,
            "202": ccxt.InvalidOrder,
            "203": ccxt.OrderNotFound,
            "401": ccxt.OrderNotFound,
            "402": ccxt.DDoSProtection,
        },
    })
}
/**
 * @method
 * @name btcbox#fetchMarkets
 * @description retrieves data on all markets for ace
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object[]} an array of objects representing market data
 */
func  (this *btcbox) FetchMarkets(optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ccxt.ReturnPanicError(ch)
                    params := ccxt.GetArg(optionalArgs, 0, map[string]interface{} {})
            _ = params
            var promise1 interface{} = this.PublicGetTickers()
            var promise2 interface{} = this.FetchWebEndpoint("fetchMarkets", "webApiGetAjaxCoinCoinInfo", true)
            response1response2Variable := (<-ccxt.PromiseAll([]interface{}{promise1, promise2}));
            response1 := ccxt.GetValue(response1response2Variable,0);
            response2 := ccxt.GetValue(response1response2Variable,1)
            //
            var result2Data interface{} = this.SafeDict(response2, "data", map[string]interface{} {})
            var marketIds interface{} = ccxt.ObjectKeys(response1)
            var markets interface{} = []interface{}{}
            for i := 0; ccxt.IsLessThan(i, ccxt.GetArrayLength(marketIds)); i++ {
                var marketId interface{} = ccxt.GetValue(marketIds, i)
                var symbolParts interface{} = ccxt.Split(marketId, "_")
                var baseCurr interface{} = this.SafeString(symbolParts, 0)
                var quote interface{} = this.SafeString(symbolParts, 1)
                var quoteId interface{} = ccxt.ToLower(quote)
                var id interface{} = ccxt.ToLower(baseCurr)
                var res interface{} = ccxt.GetValue(response1, marketId)
                var symbol interface{} = ccxt.Add(ccxt.Add(baseCurr, "/"), quote)
                var fee interface{} = ccxt.Ternary(ccxt.IsTrue((ccxt.IsEqual(id, "BTC"))), this.ParseNumber("0.0005"), this.ParseNumber("0.0010"))
                var details interface{} = this.SafeDict(result2Data, id, map[string]interface{} {})
                var tradeDetails interface{} = this.SafeDict(details, "trade", map[string]interface{} {})
                ccxt.AppendToArray(&markets, this.SafeMarketStructure(map[string]interface{} {
                    "id": id,
                    "uppercaseId": nil,
                    "symbol": symbol,
                    "base": baseCurr,
                    "baseId": id,
                    "quote": quote,
                    "quoteId": quoteId,
                    "settle": nil,
                    "settleId": nil,
                    "type": "spot",
                    "spot": true,
                    "margin": false,
                    "swap": false,
                    "future": false,
                    "option": false,
                    "taker": fee,
                    "maker": fee,
                    "contract": false,
                    "linear": nil,
                    "inverse": nil,
                    "contractSize": nil,
                    "expiry": nil,
                    "expiryDatetime": nil,
                    "strike": nil,
                    "optionType": nil,
                    "limits": map[string]interface{} {
                        "amount": map[string]interface{} {
                            "min": nil,
                            "max": nil,
                        },
                        "price": map[string]interface{} {
                            "min": nil,
                            "max": nil,
                        },
                        "cost": map[string]interface{} {
                            "min": nil,
                            "max": nil,
                        },
                        "leverage": map[string]interface{} {
                            "min": nil,
                            "max": nil,
                        },
                    },
                    "precision": map[string]interface{} {
                        "price": this.ParseNumber(this.ParsePrecision(this.SafeString(tradeDetails, "pricedecimal"))),
                        "amount": nil,
                    },
                    "active": ccxt.IsEqual(this.SafeString(tradeDetails, "enable"), "1"),
                    "created": nil,
                    "info": res,
                }))
            }
        
            ch <- markets
            return nil
        
            }()
            return ch
        }
func  (this *btcbox) ParseMarket(market interface{}) interface{}  {
    var baseId interface{} = this.SafeString(market, "base")
    var base interface{} = this.SafeCurrencyCode(baseId)
    var quoteId interface{} = this.SafeString(market, "quote")
    var quote interface{} = this.SafeCurrencyCode(quoteId)
    var symbol interface{} = ccxt.Add(ccxt.Add(base, "/"), quote)
    return map[string]interface{} {
        "id": this.SafeString(market, "symbol"),
        "uppercaseId": nil,
        "symbol": symbol,
        "base": base,
        "baseId": baseId,
        "quote": quote,
        "quoteId": quoteId,
        "settle": nil,
        "settleId": nil,
        "type": "spot",
        "spot": true,
        "margin": false,
        "swap": false,
        "future": false,
        "option": false,
        "contract": false,
        "linear": nil,
        "inverse": nil,
        "contractSize": nil,
        "expiry": nil,
        "expiryDatetime": nil,
        "strike": nil,
        "optionType": nil,
        "limits": map[string]interface{} {
            "amount": map[string]interface{} {
                "min": this.SafeNumber(market, "minLimitBaseAmount"),
                "max": this.SafeNumber(market, "maxLimitBaseAmount"),
            },
            "price": map[string]interface{} {
                "min": nil,
                "max": nil,
            },
            "cost": map[string]interface{} {
                "min": nil,
                "max": nil,
            },
            "leverage": map[string]interface{} {
                "min": nil,
                "max": nil,
            },
        },
        "precision": map[string]interface{} {
            "price": this.ParseNumber(this.ParsePrecision(this.SafeString(market, "quotePrecision"))),
            "amount": this.ParseNumber(this.ParsePrecision(this.SafeString(market, "basePrecision"))),
        },
        "active": nil,
        "created": nil,
        "info": market,
    }
}
func  (this *btcbox) ParseBalance(response interface{}) interface{}  {
    var result interface{} = map[string]interface{} {
        "info": response,
    }
    var codes interface{} = ccxt.ObjectKeys(this.Currencies)
    for i := 0; ccxt.IsLessThan(i, ccxt.GetArrayLength(codes)); i++ {
        var code interface{} = ccxt.GetValue(codes, i)
        var currency interface{} = this.Currency(code)
        var currencyId interface{} = ccxt.GetValue(currency, "id")
        var free interface{} = ccxt.Add(currencyId, "_balance")
        if ccxt.IsTrue(ccxt.InOp(response, free)) {
            var account interface{} = this.Account()
            var used interface{} = ccxt.Add(currencyId, "_lock")
            ccxt.AddElementToObject(account, "free", this.SafeString(response, free))
            ccxt.AddElementToObject(account, "used", this.SafeString(response, used))
            ccxt.AddElementToObject(result, code, account)
        }
    }
    return this.SafeBalance(result)
}
/**
 * @method
 * @name btcbox#fetchBalance
 * @description query for balance and get the amount of funds available for trading or funds locked in orders
 * @see https://blog.btcbox.jp/en/archives/8762#toc13
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} a [balance structure]{@link https://docs.ccxt.com/#/?id=balance-structure}
 */
func  (this *btcbox) FetchBalance(optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ccxt.ReturnPanicError(ch)
                    params := ccxt.GetArg(optionalArgs, 0, map[string]interface{} {})
            _ = params
        
            retRes4048 := (<-this.LoadMarkets())
            ccxt.PanicOnError(retRes4048)
        
            response:= (<-this.PrivatePostBalance(params))
            ccxt.PanicOnError(response)
        
            ch <- this.ParseBalance(response)
            return nil
        
            }()
            return ch
        }
/**
 * @method
 * @name btcbox#fetchOrderBook
 * @description fetches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
 * @see https://blog.btcbox.jp/en/archives/8762#toc6
 * @param {string} symbol unified symbol of the market to fetch the order book for
 * @param {int} [limit] the maximum amount of order book entries to return
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} A dictionary of [order book structures]{@link https://docs.ccxt.com/#/?id=order-book-structure} indexed by market symbols
 */
func  (this *btcbox) FetchOrderBook(symbol interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ccxt.ReturnPanicError(ch)
                    limit := ccxt.GetArg(optionalArgs, 0, nil)
            _ = limit
            params := ccxt.GetArg(optionalArgs, 1, map[string]interface{} {})
            _ = params
        
            retRes4208 := (<-this.LoadMarkets())
            ccxt.PanicOnError(retRes4208)
            var market interface{} = this.Market(symbol)
            var request interface{} = map[string]interface{} {}
            var numSymbols interface{} =     ccxt.GetArrayLength(this.Symbols)
            if ccxt.IsTrue(ccxt.IsGreaterThan(numSymbols, 1)) {
                ccxt.AddElementToObject(request, "coin", ccxt.GetValue(market, "baseId"))
            }
        
            response:= (<-this.PublicGetDepth(this.Extend(request, params)))
            ccxt.PanicOnError(response)
        
            ch <- this.ParseOrderBook(response, ccxt.GetValue(market, "symbol"))
            return nil
        
            }()
            return ch
        }
func  (this *btcbox) ParseTicker(ticker interface{}, optionalArgs ...interface{}) interface{}  {
    market := ccxt.GetArg(optionalArgs, 0, nil)
    _ = market
    var symbol interface{} = this.SafeSymbol(nil, market)
    var last interface{} = this.SafeString(ticker, "last")
    return this.SafeTicker(map[string]interface{} {
        "symbol": symbol,
        "timestamp": nil,
        "datetime": nil,
        "high": this.SafeString(ticker, "high"),
        "low": this.SafeString(ticker, "low"),
        "bid": this.SafeString(ticker, "buy"),
        "bidVolume": nil,
        "ask": this.SafeString(ticker, "sell"),
        "askVolume": nil,
        "vwap": nil,
        "open": nil,
        "close": last,
        "last": last,
        "previousClose": nil,
        "change": nil,
        "percentage": nil,
        "average": nil,
        "baseVolume": this.SafeString(ticker, "vol"),
        "quoteVolume": this.SafeString(ticker, "volume"),
        "info": ticker,
    }, market)
}
/**
 * @method
 * @name btcbox#fetchTicker
 * @description fetches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market
 * @see https://blog.btcbox.jp/en/archives/8762#toc5
 * @param {string} symbol unified symbol of the market to fetch the ticker for
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/#/?id=ticker-structure}
 */
func  (this *btcbox) FetchTicker(symbol interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ccxt.ReturnPanicError(ch)
                    params := ccxt.GetArg(optionalArgs, 0, map[string]interface{} {})
            _ = params
        
            retRes4688 := (<-this.LoadMarkets())
            ccxt.PanicOnError(retRes4688)
            var market interface{} = this.Market(symbol)
            var request interface{} = map[string]interface{} {}
            var numSymbols interface{} =     ccxt.GetArrayLength(this.Symbols)
            if ccxt.IsTrue(ccxt.IsGreaterThan(numSymbols, 1)) {
                ccxt.AddElementToObject(request, "coin", ccxt.GetValue(market, "baseId"))
            }
        
            response:= (<-this.PublicGetTicker(this.Extend(request, params)))
            ccxt.PanicOnError(response)
        
            ch <- this.ParseTicker(response, market)
            return nil
        
            }()
            return ch
        }
/**
 * @method
 * @name btcbox#fetchTickers
 * @description fetches price tickers for multiple markets, statistical information calculated over the past 24 hours for each market
 * @param {string[]} [symbols] unified symbols of the markets to fetch the ticker for, all market tickers are returned if not assigned
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} a dictionary of [ticker structures]{@link https://docs.ccxt.com/#/?id=ticker-structure}
 */
func  (this *btcbox) FetchTickers(optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ccxt.ReturnPanicError(ch)
                    symbols := ccxt.GetArg(optionalArgs, 0, nil)
            _ = symbols
            params := ccxt.GetArg(optionalArgs, 1, map[string]interface{} {})
            _ = params
        
            retRes4888 := (<-this.LoadMarkets())
            ccxt.PanicOnError(retRes4888)
        
            response:= (<-this.PublicGetTickers(params))
            ccxt.PanicOnError(response)
        
            ch <- this.ParseTickers(response, symbols)
            return nil
        
            }()
            return ch
        }
func  (this *btcbox) ParseTrade(trade interface{}, optionalArgs ...interface{}) interface{}  {
    //
    // fetchTrades (public)
    //
    //      {
    //          "date":"0",
    //          "price":3,
    //          "amount":0.1,
    //          "tid":"1",
    //          "type":"buy"
    //      }
    //
    market := ccxt.GetArg(optionalArgs, 0, nil)
    _ = market
    var timestamp interface{} = this.SafeTimestamp(trade, "date")
    market = this.SafeMarket(nil, market)
    var id interface{} = this.SafeString(trade, "tid")
    var priceString interface{} = this.SafeString(trade, "price")
    var amountString interface{} = this.SafeString(trade, "amount")
    var typeVar interface{} = nil
    var side interface{} = this.SafeString(trade, "type")
    return this.SafeTrade(map[string]interface{} {
        "info": trade,
        "id": id,
        "order": nil,
        "timestamp": timestamp,
        "datetime": this.Iso8601(timestamp),
        "symbol": ccxt.GetValue(market, "symbol"),
        "type": typeVar,
        "side": side,
        "takerOrMaker": nil,
        "price": priceString,
        "amount": amountString,
        "cost": nil,
        "fee": nil,
    }, market)
}
/**
 * @method
 * @name btcbox#fetchTrades
 * @description get the list of most recent trades for a particular symbol
 * @see https://blog.btcbox.jp/en/archives/8762#toc7
 * @param {string} symbol unified symbol of the market to fetch trades for
 * @param {int} [since] timestamp in ms of the earliest trade to fetch
 * @param {int} [limit] the maximum amount of trades to fetch
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {ccxt.Trade[]} a list of [trade structures]{@link https://docs.ccxt.com/#/?id=public-trades}
 */
func  (this *btcbox) FetchTrades(symbol interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ccxt.ReturnPanicError(ch)
                    since := ccxt.GetArg(optionalArgs, 0, nil)
            _ = since
            limit := ccxt.GetArg(optionalArgs, 1, nil)
            _ = limit
            params := ccxt.GetArg(optionalArgs, 2, map[string]interface{} {})
            _ = params
        
            retRes5418 := (<-this.LoadMarkets())
            ccxt.PanicOnError(retRes5418)
            var market interface{} = this.Market(symbol)
            var request interface{} = map[string]interface{} {}
            var numSymbols interface{} =     ccxt.GetArrayLength(this.Symbols)
            if ccxt.IsTrue(ccxt.IsGreaterThan(numSymbols, 1)) {
                ccxt.AddElementToObject(request, "coin", ccxt.GetValue(market, "baseId"))
            }
        
            response:= (<-this.PublicGetOrders(this.Extend(request, params)))
            ccxt.PanicOnError(response)
        
                //
            //     [
            //          {
            //              "date":"0",
            //              "price":3,
            //              "amount":0.1,
            //              "tid":"1",
            //              "type":"buy"
            //          },
            //     ]
            //
        ch <- this.ParseTrades(response, market, since, limit)
            return nil
        
            }()
            return ch
        }
/**
 * @method
 * @name btcbox#createOrder
 * @description create a trade order
 * @see https://blog.btcbox.jp/en/archives/8762#toc18
 * @param {string} symbol unified symbol of the market to create an order in
 * @param {string} type 'market' or 'limit'
 * @param {string} side 'buy' or 'sell'
 * @param {float} amount how much of currency you want to trade in units of base currency
 * @param {float} [price] the price at which the order is to be fulfilled, in units of the quote currency, ignored in market orders
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} an [order structure]{@link https://docs.ccxt.com/#/?id=order-structure}
 */
func  (this *btcbox) CreateOrder(symbol interface{}, typeVar interface{}, side interface{}, amount interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ccxt.ReturnPanicError(ch)
                    price := ccxt.GetArg(optionalArgs, 0, nil)
            _ = price
            params := ccxt.GetArg(optionalArgs, 1, map[string]interface{} {})
            _ = params
        
            retRes5778 := (<-this.LoadMarkets())
            ccxt.PanicOnError(retRes5778)
            var market interface{} = this.Market(symbol)
            var request interface{} = map[string]interface{} {
                "amount": amount,
                "price": price,
                "type": side,
                "coin": ccxt.GetValue(market, "baseId"),
            }
        
            response:= (<-this.PrivatePostTradeAdd(this.Extend(request, params)))
            ccxt.PanicOnError(response)
        
                //
            //     {
            //         "result":true,
            //         "id":"11"
            //     }
            //
        ch <- this.ParseOrder(response, market)
            return nil
        
            }()
            return ch
        }
/**
 * @method
 * @name btcbox#cancelOrder
 * @description cancels an open order
 * @see https://blog.btcbox.jp/en/archives/8762#toc17
 * @param {string} id order id
 * @param {string} symbol unified symbol of the market the order was made in
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} An [order structure]{@link https://docs.ccxt.com/#/?id=order-structure}
 */
func  (this *btcbox) CancelOrder(id interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ccxt.ReturnPanicError(ch)
                    symbol := ccxt.GetArg(optionalArgs, 0, nil)
            _ = symbol
            params := ccxt.GetArg(optionalArgs, 1, map[string]interface{} {})
            _ = params
        
            retRes6068 := (<-this.LoadMarkets())
            ccxt.PanicOnError(retRes6068)
            // a special case for btcbox – default symbol is BTC/JPY
            if ccxt.IsTrue(ccxt.IsEqual(symbol, nil)) {
                symbol = "BTC/JPY"
            }
            var market interface{} = this.Market(symbol)
            var request interface{} = map[string]interface{} {
                "id": id,
                "coin": ccxt.GetValue(market, "baseId"),
            }
        
            response:= (<-this.PrivatePostTradeCancel(this.Extend(request, params)))
            ccxt.PanicOnError(response)
        
                //
            //     {"result":true, "id":"11"}
            //
        ch <- this.ParseOrder(response, market)
            return nil
        
            }()
            return ch
        }
func  (this *btcbox) ParseOrderStatus(status interface{}) interface{}  {
    var statuses interface{} = map[string]interface{} {
        "part": "open",
        "all": "closed",
        "cancelled": "canceled",
        "closed": "closed",
        "no": "closed",
    }
    return this.SafeString(statuses, status, status)
}
func  (this *btcbox) ParseOrder(order interface{}, optionalArgs ...interface{}) interface{}  {
    //
    //     {
    //         "id":11,
    //         "datetime":"2014-10-21 10:47:20",
    //         "type":"sell",
    //         "price":42000,
    //         "amount_original":1.2,
    //         "amount_outstanding":1.2,
    //         "status":"closed",
    //         "trades":[] // no clarification of trade value structure of order endpoint
    //     }
    //
    market := ccxt.GetArg(optionalArgs, 0, nil)
    _ = market
    var id interface{} = this.SafeString(order, "id")
    var datetimeString interface{} = this.SafeString(order, "datetime")
    var timestamp interface{} = nil
    if ccxt.IsTrue(!ccxt.IsEqual(datetimeString, nil)) {
        timestamp = this.Parse8601(ccxt.Add(ccxt.GetValue(order, "datetime"), "+09:00")) // Tokyo time
    }
    var amount interface{} = this.SafeString(order, "amount_original")
    var remaining interface{} = this.SafeString(order, "amount_outstanding")
    var price interface{} = this.SafeString(order, "price")
    // status is set by fetchOrder method only
    var status interface{} = this.ParseOrderStatus(this.SafeString(order, "status"))
    // fetchOrders do not return status, use heuristic
    if ccxt.IsTrue(ccxt.IsEqual(status, nil)) {
        if ccxt.IsTrue(ccxt.Precise.StringEquals(remaining, "0")) {
            status = "closed"
        }
    }
    var trades interface{} = nil // todo: this.parseTrades (order['trades']);
    market = this.SafeMarket(nil, market)
    var side interface{} = this.SafeString(order, "type")
    return this.SafeOrder(map[string]interface{} {
        "id": id,
        "clientOrderId": nil,
        "timestamp": timestamp,
        "datetime": this.Iso8601(timestamp),
        "lastTradeTimestamp": nil,
        "amount": amount,
        "remaining": remaining,
        "filled": nil,
        "side": side,
        "type": nil,
        "timeInForce": nil,
        "postOnly": nil,
        "status": status,
        "symbol": ccxt.GetValue(market, "symbol"),
        "price": price,
        "triggerPrice": nil,
        "cost": nil,
        "trades": trades,
        "fee": nil,
        "info": order,
        "average": nil,
    }, market)
}
/**
 * @method
 * @name btcbox#fetchOrder
 * @description fetches information on an order made by the user
 * @see https://blog.btcbox.jp/en/archives/8762#toc16
 * @param {string} id the order id
 * @param {string} symbol unified symbol of the market the order was made in
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} An [order structure]{@link https://docs.ccxt.com/#/?id=order-structure}
 */
func  (this *btcbox) FetchOrder(id interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ccxt.ReturnPanicError(ch)
                    symbol := ccxt.GetArg(optionalArgs, 0, nil)
            _ = symbol
            params := ccxt.GetArg(optionalArgs, 1, map[string]interface{} {})
            _ = params
        
            retRes7048 := (<-this.LoadMarkets())
            ccxt.PanicOnError(retRes7048)
            // a special case for btcbox – default symbol is BTC/JPY
            if ccxt.IsTrue(ccxt.IsEqual(symbol, nil)) {
                symbol = "BTC/JPY"
            }
            var market interface{} = this.Market(symbol)
            var request interface{} = this.Extend(map[string]interface{} {
                "id": id,
                "coin": ccxt.GetValue(market, "baseId"),
            }, params)
        
            response:= (<-this.PrivatePostTradeView(this.Extend(request, params)))
            ccxt.PanicOnError(response)
        
                //
            //      {
            //          "id":11,
            //          "datetime":"2014-10-21 10:47:20",
            //          "type":"sell",
            //          "price":42000,
            //          "amount_original":1.2,
            //          "amount_outstanding":1.2,
            //          "status":"closed",
            //          "trades":[]
            //      }
            //
        ch <- this.ParseOrder(response, market)
            return nil
        
            }()
            return ch
        }
func  (this *btcbox) FetchOrdersByType(typeVar interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ccxt.ReturnPanicError(ch)
                    symbol := ccxt.GetArg(optionalArgs, 0, nil)
            _ = symbol
            since := ccxt.GetArg(optionalArgs, 1, nil)
            _ = since
            limit := ccxt.GetArg(optionalArgs, 2, nil)
            _ = limit
            params := ccxt.GetArg(optionalArgs, 3, map[string]interface{} {})
            _ = params
        
            retRes7318 := (<-this.LoadMarkets())
            ccxt.PanicOnError(retRes7318)
            // a special case for btcbox – default symbol is BTC/JPY
            var market interface{} = this.Market(symbol)
            var request interface{} = map[string]interface{} {
                "type": typeVar,
                "coin": ccxt.GetValue(market, "baseId"),
            }
        
            response:= (<-this.PrivatePostTradeList(this.Extend(request, params)))
            ccxt.PanicOnError(response)
            //
            // [
            //      {
            //          "id":"7",
            //          "datetime":"2014-10-20 13:27:38",
            //          "type":"buy",
            //          "price":42750,
            //          "amount_original":0.235,
            //          "amount_outstanding":0.235
            //      },
            // ]
            //
            var orders interface{} = this.ParseOrders(response, market, since, limit)
            // status (open/closed/canceled) is undefined
            // btcbox does not return status, but we know it's 'open' as we queried for open orders
            if ccxt.IsTrue(ccxt.IsEqual(typeVar, "open")) {
                for i := 0; ccxt.IsLessThan(i, ccxt.GetArrayLength(orders)); i++ {
                    ccxt.AddElementToObject(ccxt.GetValue(orders, i), "status", "open")
                }
            }
        
            ch <- orders
            return nil
        
            }()
            return ch
        }
/**
 * @method
 * @name btcbox#fetchOrders
 * @description fetches information on multiple orders made by the user
 * @see https://blog.btcbox.jp/en/archives/8762#toc15
 * @param {string} symbol unified market symbol of the market orders were made in
 * @param {int} [since] the earliest time in ms to fetch orders for
 * @param {int} [limit] the maximum number of order structures to retrieve
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {ccxt.Order[]} a list of [order structures]{@link https://docs.ccxt.com/#/?id=order-structure}
 */
func  (this *btcbox) FetchOrders(optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ccxt.ReturnPanicError(ch)
                    symbol := ccxt.GetArg(optionalArgs, 0, nil)
            _ = symbol
            since := ccxt.GetArg(optionalArgs, 1, nil)
            _ = since
            limit := ccxt.GetArg(optionalArgs, 2, nil)
            _ = limit
            params := ccxt.GetArg(optionalArgs, 3, map[string]interface{} {})
            _ = params
        
                retRes77415 :=  (<-this.FetchOrdersByType("all", symbol, since, limit, params))
                ccxt.PanicOnError(retRes77415)
                ch <- retRes77415
                return nil
        
            }()
            return ch
        }
/**
 * @method
 * @name btcbox#fetchOpenOrders
 * @description fetch all unfilled currently open orders
 * @see https://blog.btcbox.jp/en/archives/8762#toc15
 * @param {string} symbol unified market symbol
 * @param {int} [since] the earliest time in ms to fetch open orders for
 * @param {int} [limit] the maximum number of  open orders structures to retrieve
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {ccxt.Order[]} a list of [order structures]{@link https://docs.ccxt.com/#/?id=order-structure}
 */
func  (this *btcbox) FetchOpenOrders(optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ccxt.ReturnPanicError(ch)
                    symbol := ccxt.GetArg(optionalArgs, 0, nil)
            _ = symbol
            since := ccxt.GetArg(optionalArgs, 1, nil)
            _ = since
            limit := ccxt.GetArg(optionalArgs, 2, nil)
            _ = limit
            params := ccxt.GetArg(optionalArgs, 3, map[string]interface{} {})
            _ = params
        
                retRes78915 :=  (<-this.FetchOrdersByType("open", symbol, since, limit, params))
                ccxt.PanicOnError(retRes78915)
                ch <- retRes78915
                return nil
        
            }()
            return ch
        }
func  (this *btcbox) Nonce() interface{}  {
    return this.Milliseconds()
}
func  (this *btcbox) Sign(path interface{}, optionalArgs ...interface{}) interface{}  {
    api := ccxt.GetArg(optionalArgs, 0, "public")
    _ = api
    method := ccxt.GetArg(optionalArgs, 1, "GET")
    _ = method
    params := ccxt.GetArg(optionalArgs, 2, map[string]interface{} {})
    _ = params
    headers := ccxt.GetArg(optionalArgs, 3, nil)
    _ = headers
    body := ccxt.GetArg(optionalArgs, 4, nil)
    _ = body
    var url interface{} = ccxt.Add(ccxt.Add(ccxt.Add(ccxt.Add(ccxt.GetValue(ccxt.GetValue(this.Urls, "api"), "rest"), "/"), this.Version), "/"), path)
    if ccxt.IsTrue(ccxt.IsEqual(api, "public")) {
        if ccxt.IsTrue(ccxt.GetArrayLength(ccxt.ObjectKeys(params))) {
            url = ccxt.Add(url, ccxt.Add("?", this.Urlencode(params)))
        }
    } else if ccxt.IsTrue(ccxt.IsEqual(api, "webApi")) {
        url = ccxt.Add(ccxt.Add(ccxt.GetValue(this.Urls, "www"), "/"), path)
    } else {
        this.CheckRequiredCredentials()
        var nonce interface{} = ccxt.ToString(this.Nonce())
        var query interface{} = this.Extend(map[string]interface{} {
            "key": this.ApiKey,
            "nonce": nonce,
        }, params)
        var request interface{} = this.Urlencode(query)
        var secret interface{} = this.Hash(this.Encode(this.Secret), ccxt.Md5)
        ccxt.AddElementToObject(query, "signature", this.Hmac(this.Encode(request), this.Encode(secret), ccxt.Sha256))
        body = this.Urlencode(query)
        headers = map[string]interface{} {
            "Content-Type": "application/x-www-form-urlencoded",
        }
    }
    return map[string]interface{} {
        "url": url,
        "method": method,
        "body": body,
        "headers": headers,
    }
}
func  (this *btcbox) HandleErrors(httpCode interface{}, reason interface{}, url interface{}, method interface{}, headers interface{}, body interface{}, response interface{}, requestHeaders interface{}, requestBody interface{}) interface{}  {
    if ccxt.IsTrue(ccxt.IsEqual(response, nil)) {
        return nil  // resort to defaultErrorHandler
    }
    // typical error response: {"result":false,"code":"401"}
    if ccxt.IsTrue(ccxt.IsGreaterThanOrEqual(httpCode, 400)) {
        return nil  // resort to defaultErrorHandler
    }
    var result interface{} = this.SafeValue(response, "result")
    if ccxt.IsTrue(ccxt.IsTrue(ccxt.IsEqual(result, nil)) || ccxt.IsTrue(ccxt.IsEqual(result, true))) {
        return nil  // either public API (no error codes expected) or success
    }
    var code interface{} = this.SafeValue(response, "code")
    var feedback interface{} = ccxt.Add(ccxt.Add(this.Id, " "), body)
    this.ThrowExactlyMatchedException(this.Exceptions, code, feedback)
    panic(ccxt.ExchangeError(feedback))
}
func  (this *btcbox) Request(path interface{}, optionalArgs ...interface{}) <- chan interface{} {
            ch := make(chan interface{})
            go func() interface{} {
                defer close(ch)
                defer ccxt.ReturnPanicError(ch)
                    api := ccxt.GetArg(optionalArgs, 0, "public")
            _ = api
            method := ccxt.GetArg(optionalArgs, 1, "GET")
            _ = method
            params := ccxt.GetArg(optionalArgs, 2, map[string]interface{} {})
            _ = params
            headers := ccxt.GetArg(optionalArgs, 3, nil)
            _ = headers
            body := ccxt.GetArg(optionalArgs, 4, nil)
            _ = body
            config := ccxt.GetArg(optionalArgs, 5, map[string]interface{} {})
            _ = config
        
            response:= (<-this.Fetch2(path, api, method, params, headers, body, config))
            ccxt.PanicOnError(response)
            if ccxt.IsTrue(ccxt.IsString(response)) {
                // sometimes the exchange returns whitespace prepended to json
                response = this.Strip(response)
                if !ccxt.IsTrue(this.IsJsonEncodedObject(response)) {
                    panic(ccxt.ExchangeError(ccxt.Add(ccxt.Add(this.Id, " "), response)))
                }
                response = ccxt.JsonParse(response)
            }
        
            ch <- response
            return nil
        
            }()
            return ch
        }


func (this *btcbox) Init(userConfig map[string]interface{}) {
    this.Exchange = ccxt.Exchange{}
    this.Exchange.DerivedExchange = this
    this.Exchange.InitParent(userConfig, this.Describe().(map[string]interface{}), this)
}
