package onetrading

import "github.com/ccxt/ccxt/go/v4/ccxt"

type OnetradingWs struct {
   *onetradingWs
   Core *onetradingWs
}

func NewOnetradingWs(userConfig map[string]interface{}) OnetradingWs {
   p := &onetradingWs{}
   p.Init(userConfig)
   return OnetradingWs{
       onetradingWs: p,
       Core:  p,
   }
}

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


func (this *OnetradingWs) WatchBalance(params ...interface{}) (ccxt.Balances, error) {
    res := <- this.Core.WatchBalance(params...)
    if ccxt.IsError(res) {
        return ccxt.Balances{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewBalances(res), nil
}
func (this *OnetradingWs) WatchTicker(symbol string, options ...ccxt.WatchTickerOptions) (ccxt.Ticker, error) {

    opts := ccxt.WatchTickerOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.WatchTicker(symbol, params)
    if ccxt.IsError(res) {
        return ccxt.Ticker{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewTicker(res), nil
}
func (this *OnetradingWs) WatchTickers(options ...ccxt.WatchTickersOptions) (ccxt.Tickers, error) {

    opts := ccxt.WatchTickersOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var symbols interface{} = nil
    if opts.Symbols != nil {
        symbols = *opts.Symbols
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.WatchTickers(symbols, params)
    if ccxt.IsError(res) {
        return ccxt.Tickers{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewTickers(res), nil
}
func (this *OnetradingWs) WatchMyTrades(options ...ccxt.WatchMyTradesOptions) ([]ccxt.Trade, error) {

    opts := ccxt.WatchMyTradesOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var symbol interface{} = nil
    if opts.Symbol != nil {
        symbol = *opts.Symbol
    }

    var since interface{} = nil
    if opts.Since != nil {
        since = *opts.Since
    }

    var limit interface{} = nil
    if opts.Limit != nil {
        limit = *opts.Limit
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.WatchMyTrades(symbol, since, limit, params)
    if ccxt.IsError(res) {
        return nil, ccxt.CreateReturnError(res)
    }
    return ccxt.NewTradeArray(res), nil
}
func (this *OnetradingWs) WatchOrderBook(symbol string, options ...ccxt.WatchOrderBookOptions) (ccxt.IOrderBook, error) {

    opts := ccxt.WatchOrderBookOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var limit interface{} = nil
    if opts.Limit != nil {
        limit = *opts.Limit
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.WatchOrderBook(symbol, limit, params)
    if ccxt.IsError(res) {
        return ccxt.IOrderBook{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewIOrderBook(res), nil
}
func (this *OnetradingWs) WatchOrders(options ...ccxt.WatchOrdersOptions) ([]ccxt.Order, error) {

    opts := ccxt.WatchOrdersOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var symbol interface{} = nil
    if opts.Symbol != nil {
        symbol = *opts.Symbol
    }

    var since interface{} = nil
    if opts.Since != nil {
        since = *opts.Since
    }

    var limit interface{} = nil
    if opts.Limit != nil {
        limit = *opts.Limit
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.WatchOrders(symbol, since, limit, params)
    if ccxt.IsError(res) {
        return nil, ccxt.CreateReturnError(res)
    }
    return ccxt.NewOrderArray(res), nil
}
func (this *OnetradingWs) WatchOHLCV(symbol string, options ...ccxt.WatchOHLCVOptions) ([]ccxt.OHLCV, error) {

    opts := ccxt.WatchOHLCVOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var timeframe interface{} = nil
    if opts.Timeframe != nil {
        timeframe = *opts.Timeframe
    }

    var since interface{} = nil
    if opts.Since != nil {
        since = *opts.Since
    }

    var limit interface{} = nil
    if opts.Limit != nil {
        limit = *opts.Limit
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.WatchOHLCV(symbol, timeframe, since, limit, params)
    if ccxt.IsError(res) {
        return nil, ccxt.CreateReturnError(res)
    }
    return ccxt.NewOHLCVArray(res), nil
}
func (this *OnetradingWs) WatchMany(messageHash interface{}, request interface{}, subscriptionHash interface{}, symbols []string, options ...ccxt.WatchManyOptions) (map[string]interface{}, error) {

    opts := ccxt.WatchManyOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.WatchMany(messageHash, request, subscriptionHash, symbols, params)
    if ccxt.IsError(res) {
        return map[string]interface{}{}, ccxt.CreateReturnError(res)
    }
    return res.(map[string]interface{}), nil
}