// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package exmo

import ccxt "github.com/ccxt/ccxt/go/v4/ccxt"

func (this *exmo) WebGetCtrlFeesAndLimits (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("webGetCtrlFeesAndLimits", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) WebGetEnDocsFees (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("webGetEnDocsFees", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PublicGetCurrency (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetCurrency", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PublicGetCurrencyListExtended (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetCurrencyListExtended", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PublicGetOrderBook (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetOrderBook", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PublicGetPairSettings (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetPairSettings", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PublicGetTicker (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetTicker", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PublicGetTrades (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetTrades", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PublicGetCandlesHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetCandlesHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PublicGetRequiredAmount (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetRequiredAmount", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PublicGetPaymentsProvidersCryptoList (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetPaymentsProvidersCryptoList", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostUserInfo (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostUserInfo", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostOrderCreate (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostOrderCreate", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostOrderCancel (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostOrderCancel", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostStopMarketOrderCreate (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostStopMarketOrderCreate", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostStopMarketOrderCancel (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostStopMarketOrderCancel", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostUserOpenOrders (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostUserOpenOrders", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostUserTrades (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostUserTrades", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostUserCancelledOrders (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostUserCancelledOrders", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostOrderTrades (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostOrderTrades", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostDepositAddress (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostDepositAddress", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostWithdrawCrypt (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostWithdrawCrypt", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostWithdrawGetTxid (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostWithdrawGetTxid", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostExcodeCreate (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostExcodeCreate", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostExcodeLoad (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostExcodeLoad", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostCodeCheck (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostCodeCheck", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostWalletHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostWalletHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostWalletOperations (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostWalletOperations", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostMarginUserOrderCreate (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostMarginUserOrderCreate", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostMarginUserOrderUpdate (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostMarginUserOrderUpdate", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostMarginUserOrderCancel (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostMarginUserOrderCancel", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostMarginUserPositionClose (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostMarginUserPositionClose", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostMarginUserPositionMarginAdd (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostMarginUserPositionMarginAdd", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostMarginUserPositionMarginRemove (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostMarginUserPositionMarginRemove", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostMarginCurrencyList (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostMarginCurrencyList", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostMarginPairList (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostMarginPairList", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostMarginSettings (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostMarginSettings", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostMarginFundingList (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostMarginFundingList", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostMarginUserInfo (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostMarginUserInfo", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostMarginUserOrderList (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostMarginUserOrderList", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostMarginUserOrderHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostMarginUserOrderHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostMarginUserOrderTrades (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostMarginUserOrderTrades", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostMarginUserOrderMaxQuantity (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostMarginUserOrderMaxQuantity", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostMarginUserPositionList (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostMarginUserPositionList", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostMarginUserPositionMarginRemoveInfo (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostMarginUserPositionMarginRemoveInfo", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostMarginUserPositionMarginAddInfo (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostMarginUserPositionMarginAddInfo", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostMarginUserWalletList (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostMarginUserWalletList", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostMarginUserWalletHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostMarginUserWalletHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostMarginUserTradeList (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostMarginUserTradeList", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostMarginTrades (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostMarginTrades", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *exmo) PrivatePostMarginLiquidationFeed (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostMarginLiquidationFeed", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}
