// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package bitflyer

import ccxt "github.com/ccxt/ccxt/go/v4/ccxt"

func (this *bitflyer) PublicGetGetmarketsUsa (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetGetmarketsUsa", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PublicGetGetmarketsEu (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetGetmarketsEu", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PublicGetGetmarkets (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetGetmarkets", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PublicGetGetboard (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetGetboard", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PublicGetGetticker (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetGetticker", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PublicGetGetexecutions (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetGetexecutions", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PublicGetGethealth (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetGethealth", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PublicGetGetboardstate (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetGetboardstate", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PublicGetGetchats (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetGetchats", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PublicGetGetfundingrate (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetGetfundingrate", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PrivateGetGetpermissions (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetGetpermissions", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PrivateGetGetbalance (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetGetbalance", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PrivateGetGetbalancehistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetGetbalancehistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PrivateGetGetcollateral (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetGetcollateral", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PrivateGetGetcollateralhistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetGetcollateralhistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PrivateGetGetcollateralaccounts (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetGetcollateralaccounts", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PrivateGetGetaddresses (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetGetaddresses", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PrivateGetGetcoinins (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetGetcoinins", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PrivateGetGetcoinouts (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetGetcoinouts", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PrivateGetGetbankaccounts (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetGetbankaccounts", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PrivateGetGetdeposits (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetGetdeposits", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PrivateGetGetwithdrawals (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetGetwithdrawals", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PrivateGetGetchildorders (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetGetchildorders", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PrivateGetGetparentorders (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetGetparentorders", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PrivateGetGetparentorder (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetGetparentorder", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PrivateGetGetexecutions (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetGetexecutions", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PrivateGetGetpositions (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetGetpositions", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PrivateGetGettradingcommission (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetGettradingcommission", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PrivatePostSendcoin (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostSendcoin", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PrivatePostWithdraw (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostWithdraw", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PrivatePostSendchildorder (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostSendchildorder", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PrivatePostCancelchildorder (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostCancelchildorder", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PrivatePostSendparentorder (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostSendparentorder", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PrivatePostCancelparentorder (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostCancelparentorder", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *bitflyer) PrivatePostCancelallchildorders (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostCancelallchildorders", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}
