package apex

import "github.com/ccxt/ccxt/go/v4/ccxt"

type Apex struct {
   *apex
   Core *apex
}

func NewApex(userConfig map[string]interface{}) Apex {
   p := &apex{}
   p.Init(userConfig)
   return Apex{
       apex: p,
       Core:  p,
   }
}

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


/**
 * @method
 * @name apex#fetchTime
 * @description fetches the current integer timestamp in milliseconds from the exchange server
 * @see https://api-docs.pro.apex.exchange/#publicapi-v3-for-omni-get-system-time-v3
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {int} the current integer timestamp in milliseconds from the exchange server
 */
func (this *Apex) FetchTime(params ...interface{}) ( int64, error) {
    res := <- this.Core.FetchTime(params...)
    if ccxt.IsError(res) {
        return -1, ccxt.CreateReturnError(res)
    }
    return (res).(int64), nil
}
/**
 * @method
 * @name apex#fetchBalance
 * @description query for account info
 * @see https://api-docs.pro.apex.exchange/#privateapi-v3-for-omni-get-retrieve-user-account-balance
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} a [balance structure]{@link https://docs.ccxt.com/#/?id=balance-structure}
 */
func (this *Apex) FetchBalance(params ...interface{}) (ccxt.Balances, error) {
    res := <- this.Core.FetchBalance(params...)
    if ccxt.IsError(res) {
        return ccxt.Balances{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewBalances(res), nil
}
/**
 * @method
 * @name apex#fetchAccount
 * @description query for balance and get the amount of funds available for trading or funds locked in orders
 * @see https://api-docs.pro.apex.exchange/#privateapi-v3-for-omni-get-retrieve-user-account-data
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} a [balance structure]{@link https://docs.ccxt.com/#/?id=balance-structure}
 */
func (this *Apex) FetchAccount(params ...interface{}) (ccxt.Account, error) {
    res := <- this.Core.FetchAccount(params...)
    if ccxt.IsError(res) {
        return ccxt.Account{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewAccount(res), nil
}
/**
 * @method
 * @name apex#fetchCurrencies
 * @description fetches all available currencies on an exchange
 * @see https://api-docs.pro.apex.exchange/#publicapi-v3-for-omni-get-all-config-data-v3
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} an associative dictionary of currencies
 */
func (this *Apex) FetchCurrencies(params ...interface{}) (ccxt.Currencies, error) {
    res := <- this.Core.FetchCurrencies(params...)
    if ccxt.IsError(res) {
        return ccxt.Currencies{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewCurrencies(res), nil
}
/**
 * @method
 * @name apex#fetchMarkets
 * @description retrieves data on all markets for apex
 * @see https://api-docs.pro.apex.exchange/#publicapi-v3-for-omni-get-all-config-data-v3
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object[]} an array of objects representing market data
 */
func (this *Apex) FetchMarkets(params ...interface{}) ([]ccxt.MarketInterface, error) {
    res := <- this.Core.FetchMarkets(params...)
    if ccxt.IsError(res) {
        return nil, ccxt.CreateReturnError(res)
    }
    return ccxt.NewMarketInterfaceArray(res), nil
}
/**
 * @method
 * @name apex#fetchTicker
 * @description fetches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market
 * @see https://api-docs.pro.apex.exchange/#publicapi-v3-for-omni-get-ticker-data-v3
 * @param {string} symbol unified symbol of the market to fetch the ticker for
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/#/?id=ticker-structure}
 */
func (this *Apex) FetchTicker(symbol string, options ...ccxt.FetchTickerOptions) (ccxt.Ticker, error) {

    opts := ccxt.FetchTickerOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.FetchTicker(symbol, params)
    if ccxt.IsError(res) {
        return ccxt.Ticker{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewTicker(res), nil
}
/**
 * @method
 * @name apex#fetchTickers
 * @description fetches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market
 * @see https://api-docs.pro.apex.exchange/#publicapi-v3-for-omni-get-ticker-data-v3
 * @param {string} symbols unified symbol of the market to fetch the ticker for
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/#/?id=ticker-structure}
 */
func (this *Apex) FetchTickers(options ...ccxt.FetchTickersOptions) (ccxt.Tickers, error) {

    opts := ccxt.FetchTickersOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var symbols interface{} = nil
    if opts.Symbols != nil {
        symbols = *opts.Symbols
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.FetchTickers(symbols, params)
    if ccxt.IsError(res) {
        return ccxt.Tickers{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewTickers(res), nil
}
/**
 * @method
 * @name apex#fetchOHLCV
 * @description fetches historical candlestick data containing the open, high, low, and close price, and the volume of a market
 * @see https://api-docs.pro.apex.exchange/#publicapi-v3-for-omni-get-candlestick-chart-data-v3
 * @param {string} symbol unified symbol of the market to fetch ccxt.OHLCV data for
 * @param {string} timeframe the length of time each candle represents
 * @param {int} [since] timestamp in ms of the earliest candle to fetch
 * @param {int} [limit] the maximum amount of candles to fetch
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @param {int} [params.until] timestamp in ms of the latest candle to fetch
 * @returns {int[][]} A list of candles ordered as timestamp, open, high, low, close, volume
 */
func (this *Apex) FetchOHLCV(symbol string, options ...ccxt.FetchOHLCVOptions) ([]ccxt.OHLCV, error) {

    opts := ccxt.FetchOHLCVOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var timeframe interface{} = nil
    if opts.Timeframe != nil {
        timeframe = *opts.Timeframe
    }

    var since interface{} = nil
    if opts.Since != nil {
        since = *opts.Since
    }

    var limit interface{} = nil
    if opts.Limit != nil {
        limit = *opts.Limit
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.FetchOHLCV(symbol, timeframe, since, limit, params)
    if ccxt.IsError(res) {
        return nil, ccxt.CreateReturnError(res)
    }
    return ccxt.NewOHLCVArray(res), nil
}
/**
 * @method
 * @name apex#fetchOrderBook
 * @description fetches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
 * @see https://api-docs.pro.apex.exchange/#publicapi-v3-for-omni-get-market-depth-v3
 * @param {string} symbol unified symbol of the market to fetch the order book for
 * @param {int} [limit] the maximum amount of order book entries to return
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} A dictionary of [order book structures]{@link https://docs.ccxt.com/#/?id=order-book-structure} indexed by market symbols
 */
func (this *Apex) FetchOrderBook(symbol string, options ...ccxt.FetchOrderBookOptions) (ccxt.OrderBook, error) {

    opts := ccxt.FetchOrderBookOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var limit interface{} = nil
    if opts.Limit != nil {
        limit = *opts.Limit
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.FetchOrderBook(symbol, limit, params)
    if ccxt.IsError(res) {
        return ccxt.OrderBook{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewOrderBook(res), nil
}
/**
 * @method
 * @name apex#fetchTrades
 * @description get the list of most recent trades for a particular symbol
 * @see https://api-docs.pro.apex.exchange/#publicapi-v3-for-omni-get-newest-trading-data-v3
 * @param {string} symbol unified symbol of the market to fetch trades for
 * @param {int} [since] timestamp in ms of the earliest trade to fetch
 * @param {int} [limit] the maximum amount of trades to fetch
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @param {int} [params.until] the latest time in ms to fetch trades for
 * @param {boolean} [params.paginate] default false, when true will automatically paginate by calling this endpoint multiple times
 * @returns {ccxt.Trade[]} a list of [trade structures]{@link https://docs.ccxt.com/#/?id=public-trades}
 */
func (this *Apex) FetchTrades(symbol string, options ...ccxt.FetchTradesOptions) ([]ccxt.Trade, error) {

    opts := ccxt.FetchTradesOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var since interface{} = nil
    if opts.Since != nil {
        since = *opts.Since
    }

    var limit interface{} = nil
    if opts.Limit != nil {
        limit = *opts.Limit
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.FetchTrades(symbol, since, limit, params)
    if ccxt.IsError(res) {
        return nil, ccxt.CreateReturnError(res)
    }
    return ccxt.NewTradeArray(res), nil
}
/**
 * @method
 * @name apex#fetchOpenInterest
 * @description retrieves the open interest of a contract trading pair
 * @see https://api-docs.pro.apex.exchange/#publicapi-v3-for-omni-get-ticker-data-v3
 * @param {string} symbol unified CCXT market symbol
 * @param {object} [params] exchange specific parameters
 * @returns {object} an open interest structure{@link https://docs.ccxt.com/#/?id=open-interest-structure}
 */
func (this *Apex) FetchOpenInterest(symbol string, options ...ccxt.FetchOpenInterestOptions) (ccxt.OpenInterest, error) {

    opts := ccxt.FetchOpenInterestOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.FetchOpenInterest(symbol, params)
    if ccxt.IsError(res) {
        return ccxt.OpenInterest{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewOpenInterest(res), nil
}
/**
 * @method
 * @name apex#fetchFundingRateHistory
 * @description fetches historical funding rate prices
 * @see https://api-docs.pro.apex.exchange/#publicapi-v3-for-omni-get-funding-rate-history-v3
 * @param {string} symbol unified symbol of the market to fetch the funding rate history for
 * @param {int} [since] timestamp in ms of the earliest funding rate to fetch
 * @param {int} [limit] the maximum amount of [funding rate structures]{@link https://docs.ccxt.com/#/?id=funding-rate-history-structure} to fetch
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @param {int} [params.until] timestamp in ms of the latest funding rate
 * @param {boolean} [params.paginate] default false, when true will automatically paginate by calling this endpoint multiple times. See in the docs all the [availble parameters](https://github.com/ccxt/ccxt/wiki/Manual#pagination-params)
 * @returns {object[]} a list of [funding rate structures]{@link https://docs.ccxt.com/#/?id=funding-rate-history-structure}
 */
func (this *Apex) FetchFundingRateHistory(options ...ccxt.FetchFundingRateHistoryOptions) ([]ccxt.FundingRateHistory, error) {

    opts := ccxt.FetchFundingRateHistoryOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var symbol interface{} = nil
    if opts.Symbol != nil {
        symbol = *opts.Symbol
    }

    var since interface{} = nil
    if opts.Since != nil {
        since = *opts.Since
    }

    var limit interface{} = nil
    if opts.Limit != nil {
        limit = *opts.Limit
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.FetchFundingRateHistory(symbol, since, limit, params)
    if ccxt.IsError(res) {
        return nil, ccxt.CreateReturnError(res)
    }
    return ccxt.NewFundingRateHistoryArray(res), nil
}
/**
 * @method
 * @name apex#createOrder
 * @description create a trade order
 * @see https://api-docs.pro.apex.exchange/#privateapi-v3-for-omni-post-creating-orders
 * @param {string} symbol unified symbol of the market to create an order in
 * @param {string} type 'market' or 'limit'
 * @param {string} side 'buy' or 'sell'
 * @param {float} amount how much of currency you want to trade in units of base currency
 * @param {float} [price] the price at which the order is to be fullfilled, in units of the quote currency, ignored in market orders
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @param {float} [params.triggerPrice] The price a trigger order is triggered at
 * @param {string} [params.timeInForce] "GTC", "IOC", or "POST_ONLY"
 * @param {bool} [params.postOnly] true or false
 * @param {bool} [params.reduceOnly] Ensures that the executed order does not flip the opened position.
 * @param {string} [params.clientOrderId] a unique id for the order
 * @returns {object} an [order structure]{@link https://docs.ccxt.com/#/?id=order-structure}
 */
func (this *Apex) CreateOrder(symbol string, typeVar string, side string, amount float64, options ...ccxt.CreateOrderOptions) (ccxt.Order, error) {

    opts := ccxt.CreateOrderOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var price interface{} = nil
    if opts.Price != nil {
        price = *opts.Price
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.CreateOrder(symbol, typeVar, side, amount, price, params)
    if ccxt.IsError(res) {
        return ccxt.Order{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewOrder(res), nil
}
/**
 * @method
 * @name apex#transfer
 * @description transfer currency internally between wallets on the same account
 * @param {string} code unified currency code
 * @param {float} amount amount to transfer
 * @param {string} fromAccount account to transfer from
 * @param {string} toAccount account to transfer to
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @param {string} [params.transferId] UUID, which is unique across the platform
 * @returns {object} a [transfer structure]{@link https://docs.ccxt.com/#/?id=transfer-structure}
 */
func (this *Apex) Transfer(code string, amount float64, fromAccount string, toAccount string, options ...ccxt.TransferOptions) (ccxt.TransferEntry, error) {

    opts := ccxt.TransferOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.Transfer(code, amount, fromAccount, toAccount, params)
    if ccxt.IsError(res) {
        return ccxt.TransferEntry{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewTransferEntry(res), nil
}
/**
 * @method
 * @name apex#cancelAllOrders
 * @description cancel all open orders in a market
 * @see https://api-docs.pro.apex.exchange/#privateapi-v3-for-omni-post-cancel-all-open-orders
 * @param {string} symbol unified market symbol of the market to cancel orders in
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object[]} a list of [order structures]{@link https://docs.ccxt.com/#/?id=order-structure}
 */
func (this *Apex) CancelAllOrders(options ...ccxt.CancelAllOrdersOptions) (map[string]interface{}, error) {

    opts := ccxt.CancelAllOrdersOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var symbol interface{} = nil
    if opts.Symbol != nil {
        symbol = *opts.Symbol
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.CancelAllOrders(symbol, params)
    if ccxt.IsError(res) {
        return map[string]interface{}{}, ccxt.CreateReturnError(res)
    }
    return res.(map[string]interface{}), nil
}
/**
 * @method
 * @name apex#cancelOrder
 * @description cancels an open order
 * @see https://api-docs.pro.apex.exchange/#privateapi-v3-for-omni-post-cancel-order
 * @param {string} id order id
 * @param symbol
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} An [order structure]{@link https://docs.ccxt.com/#/?id=order-structure}
 */
func (this *Apex) CancelOrder(id string, options ...ccxt.CancelOrderOptions) (map[string]interface{}, error) {

    opts := ccxt.CancelOrderOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var symbol interface{} = nil
    if opts.Symbol != nil {
        symbol = *opts.Symbol
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.CancelOrder(id, symbol, params)
    if ccxt.IsError(res) {
        return map[string]interface{}{}, ccxt.CreateReturnError(res)
    }
    return res.(map[string]interface{}), nil
}
/**
 * @method
 * @name apex#fetchOrder
 * @description fetches information on an order made by the user
 * @see https://api-docs.pro.apex.exchange/#privateapi-v3-for-omni-get-order-id
 * @see https://api-docs.pro.apex.exchange/#privateapi-v3-for-omni-get-order-by-clientorderid
 * @param {string} id the order id
 * @param {string} symbol unified symbol of the market the order was made in
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @param {string} [params.clientOrderId] a unique id for the order
 * @returns {object} An [order structure]{@link https://docs.ccxt.com/#/?id=order-structure}
 */
func (this *Apex) FetchOrder(id string, options ...ccxt.FetchOrderOptions) (ccxt.Order, error) {

    opts := ccxt.FetchOrderOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var symbol interface{} = nil
    if opts.Symbol != nil {
        symbol = *opts.Symbol
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.FetchOrder(id, symbol, params)
    if ccxt.IsError(res) {
        return ccxt.Order{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewOrder(res), nil
}
/**
 * @method
 * @name apex#fetchOpenOrders
 * @description fetches information on multiple orders made by the user
 * @see https://api-docs.pro.apex.exchange/#privateapi-v3-for-omni-get-open-orders
 * @param {string} symbol unified market symbol of the market orders were made in
 * @param {int} [since] the earliest time in ms to fetch orders for
 * @param {int} [limit] the maximum number of order structures to retrieve
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {ccxt.Order[]} a list of [order structures]{@link https://docs.ccxt.com/#/?id=order-structure}
 */
func (this *Apex) FetchOpenOrders(options ...ccxt.FetchOpenOrdersOptions) ([]ccxt.Order, error) {

    opts := ccxt.FetchOpenOrdersOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var symbol interface{} = nil
    if opts.Symbol != nil {
        symbol = *opts.Symbol
    }

    var since interface{} = nil
    if opts.Since != nil {
        since = *opts.Since
    }

    var limit interface{} = nil
    if opts.Limit != nil {
        limit = *opts.Limit
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.FetchOpenOrders(symbol, since, limit, params)
    if ccxt.IsError(res) {
        return nil, ccxt.CreateReturnError(res)
    }
    return ccxt.NewOrderArray(res), nil
}
/**
 * @method
 * @name apex#fetchOrders
 * @description fetches information on multiple orders made by the user *classic accounts only*
 * @see https://api-docs.pro.apex.exchange/#privateapi-v3-for-omni-get-all-order-history
 * @param {string} symbol unified market symbol of the market orders were made in
 * @param {int} [since] the earliest time in ms to fetch orders for
 * @param {int} [limit] the maximum number of order structures to retrieve, default 100
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @param {object} [params.until] end time, ms
 * @param {boolean} [params.status] "PENDING", "OPEN", "FILLED", "CANCELED", "EXPIRED", "UNTRIGGERED"
 * @param {boolean} [params.side] BUY or SELL
 * @param {string} [params.type] "LIMIT", "MARKET","STOP_LIMIT", "STOP_MARKET", "TAKE_PROFIT_LIMIT","TAKE_PROFIT_MARKET"
 * @param {string} [params.orderType] "ACTIVE","CONDITION","HISTORY"
 * @param {boolean} [params.page] Page numbers start from 0
 * @returns {ccxt.Order[]} a list of [order structures]{@link https://docs.ccxt.com/#/?id=order-structure}
 */
func (this *Apex) FetchOrders(options ...ccxt.FetchOrdersOptions) ([]ccxt.Order, error) {

    opts := ccxt.FetchOrdersOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var symbol interface{} = nil
    if opts.Symbol != nil {
        symbol = *opts.Symbol
    }

    var since interface{} = nil
    if opts.Since != nil {
        since = *opts.Since
    }

    var limit interface{} = nil
    if opts.Limit != nil {
        limit = *opts.Limit
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.FetchOrders(symbol, since, limit, params)
    if ccxt.IsError(res) {
        return nil, ccxt.CreateReturnError(res)
    }
    return ccxt.NewOrderArray(res), nil
}
/**
 * @method
 * @name apex#fetchOrderTrades
 * @description fetch all the trades made from a single order
 * @see https://api-docs.pro.apex.exchange/#privateapi-v3-for-omni-get-trade-history
 * @param {string} id order id
 * @param {string} symbol unified market symbol
 * @param {int} [since] the earliest time in ms to fetch trades for
 * @param {int} [limit] the maximum number of trades to retrieve
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object[]} a list of [trade structures]{@link https://docs.ccxt.com/#/?id=trade-structure}
 */
func (this *Apex) FetchOrderTrades(id string, options ...ccxt.FetchOrderTradesOptions) ([]ccxt.Trade, error) {

    opts := ccxt.FetchOrderTradesOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var symbol interface{} = nil
    if opts.Symbol != nil {
        symbol = *opts.Symbol
    }

    var since interface{} = nil
    if opts.Since != nil {
        since = *opts.Since
    }

    var limit interface{} = nil
    if opts.Limit != nil {
        limit = *opts.Limit
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.FetchOrderTrades(id, symbol, since, limit, params)
    if ccxt.IsError(res) {
        return nil, ccxt.CreateReturnError(res)
    }
    return ccxt.NewTradeArray(res), nil
}
/**
 * @method
 * @name apex#fetchMyTrades
 * @description fetches information on multiple orders made by the user *classic accounts only*
 * @see https://api-docs.pro.apex.exchange/#privateapi-v3-for-omni-get-trade-history
 * @param {string} symbol unified market symbol of the market orders were made in
 * @param {int} [since] the earliest time in ms to fetch orders for
 * @param {int} [limit] the maximum number of order structures to retrieve, default 100
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @param {object} [params.until] end time
 * @param {boolean} [params.side] BUY or SELL
 * @param {string} [params.orderType] "LIMIT", "MARKET","STOP_LIMIT", "STOP_MARKET", "TAKE_PROFIT_LIMIT","TAKE_PROFIT_MARKET"
 * @param {boolean} [params.page] Page numbers start from 0
 * @returns {ccxt.Trade[]} a list of [trade structures]{@link https://docs.ccxt.com/#/?id=trade-structure}
 */
func (this *Apex) FetchMyTrades(options ...ccxt.FetchMyTradesOptions) ([]ccxt.Trade, error) {

    opts := ccxt.FetchMyTradesOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var symbol interface{} = nil
    if opts.Symbol != nil {
        symbol = *opts.Symbol
    }

    var since interface{} = nil
    if opts.Since != nil {
        since = *opts.Since
    }

    var limit interface{} = nil
    if opts.Limit != nil {
        limit = *opts.Limit
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.FetchMyTrades(symbol, since, limit, params)
    if ccxt.IsError(res) {
        return nil, ccxt.CreateReturnError(res)
    }
    return ccxt.NewTradeArray(res), nil
}
/**
 * @method
 * @name apex#fetchFundingHistory
 * @description fetches information on multiple orders made by the user *classic accounts only*
 * @see https://api-docs.pro.apex.exchange/#privateapi-v3-for-omni-get-funding-rate
 * @param {string} symbol unified market symbol of the market orders were made in
 * @param {int} [since] the earliest time in ms to fetch orders for
 * @param {int} [limit] the maximum number of order structures to retrieve, default 100
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @param {object} [params.until] end time, ms
 * @param {boolean} [params.side] BUY or SELL
 * @param {boolean} [params.page] Page numbers start from 0
 * @returns {ccxt.Trade[]} a list of [trade structures]{@link https://docs.ccxt.com/#/?id=funding-history-structure}
 */
func (this *Apex) FetchFundingHistory(options ...ccxt.FetchFundingHistoryOptions) ([]ccxt.FundingHistory, error) {

    opts := ccxt.FetchFundingHistoryOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var symbol interface{} = nil
    if opts.Symbol != nil {
        symbol = *opts.Symbol
    }

    var since interface{} = nil
    if opts.Since != nil {
        since = *opts.Since
    }

    var limit interface{} = nil
    if opts.Limit != nil {
        limit = *opts.Limit
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.FetchFundingHistory(symbol, since, limit, params)
    if ccxt.IsError(res) {
        return nil, ccxt.CreateReturnError(res)
    }
    return ccxt.NewFundingHistoryArray(res), nil
}
/**
 * @method
 * @name apex#setLeverage
 * @description set the level of leverage for a market
 * @see https://api-docs.pro.apex.exchange/#privateapi-v3-for-omni-post-sets-the-initial-margin-rate-of-a-contract
 * @param {float} leverage the rate of leverage
 * @param {string} symbol unified market symbol
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} response from the exchange
 */
func (this *Apex) SetLeverage(leverage int64, options ...ccxt.SetLeverageOptions) (map[string]interface{}, error) {

    opts := ccxt.SetLeverageOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var symbol interface{} = nil
    if opts.Symbol != nil {
        symbol = *opts.Symbol
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.SetLeverage(leverage, symbol, params)
    if ccxt.IsError(res) {
        return map[string]interface{}{}, ccxt.CreateReturnError(res)
    }
    return res.(map[string]interface{}), nil
}
/**
 * @method
 * @name apex#fetchPositions
 * @description fetch all open positions
 * @see https://api-docs.pro.apex.exchange/#privateapi-v3-for-omni-get-retrieve-user-account-data
 * @param {string[]} [symbols] list of unified market symbols
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object[]} a list of [position structure]{@link https://docs.ccxt.com/#/?id=position-structure}
 */
func (this *Apex) FetchPositions(options ...ccxt.FetchPositionsOptions) ([]ccxt.Position, error) {

    opts := ccxt.FetchPositionsOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var symbols interface{} = nil
    if opts.Symbols != nil {
        symbols = *opts.Symbols
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.FetchPositions(symbols, params)
    if ccxt.IsError(res) {
        return nil, ccxt.CreateReturnError(res)
    }
    return ccxt.NewPositionArray(res), nil
}