// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package oceanex

import ccxt "github.com/ccxt/ccxt/go/v4/ccxt"

func (this *oceanex) PublicGetMarkets (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetMarkets", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *oceanex) PublicGetTickersPair (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetTickersPair", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *oceanex) PublicGetTickersMulti (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetTickersMulti", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *oceanex) PublicGetOrderBook (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetOrderBook", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *oceanex) PublicGetOrderBookMulti (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetOrderBookMulti", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *oceanex) PublicGetFeesTrading (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetFeesTrading", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *oceanex) PublicGetTrades (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetTrades", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *oceanex) PublicGetTimestamp (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetTimestamp", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *oceanex) PublicPostK (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostK", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *oceanex) PrivateGetKey (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetKey", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *oceanex) PrivateGetMembersMe (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetMembersMe", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *oceanex) PrivateGetOrders (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetOrders", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *oceanex) PrivateGetOrdersFilter (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privateGetOrdersFilter", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *oceanex) PrivatePostOrders (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostOrders", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *oceanex) PrivatePostOrdersMulti (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostOrdersMulti", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *oceanex) PrivatePostOrderDelete (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostOrderDelete", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *oceanex) PrivatePostOrderDeleteMulti (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostOrderDeleteMulti", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *oceanex) PrivatePostOrdersClear (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostOrdersClear", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *oceanex) PrivatePostWithdrawsSpecialNew (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostWithdrawsSpecialNew", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *oceanex) PrivatePostDepositAddress (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostDepositAddress", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *oceanex) PrivatePostDepositAddresses (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostDepositAddresses", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *oceanex) PrivatePostDepositHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostDepositHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *oceanex) PrivatePostWithdrawHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostWithdrawHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}
