// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package derive

import ccxt "github.com/ccxt/ccxt/go/v4/ccxt"

func (this *derive) PublicGetGetAllCurrencies (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetGetAllCurrencies", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostBuildRegisterSessionKeyTx (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostBuildRegisterSessionKeyTx", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostRegisterSessionKey (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostRegisterSessionKey", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostDeregisterSessionKey (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostDeregisterSessionKey", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostLogin (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostLogin", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostStatistics (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostStatistics", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetAllCurrencies (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetAllCurrencies", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetCurrency (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetCurrency", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetInstrument (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetInstrument", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetAllInstruments (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetAllInstruments", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetInstruments (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetInstruments", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetTicker (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetTicker", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetLatestSignedFeeds (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetLatestSignedFeeds", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetOptionSettlementPrices (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetOptionSettlementPrices", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetSpotFeedHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetSpotFeedHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetSpotFeedHistoryCandles (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetSpotFeedHistoryCandles", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetFundingRateHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetFundingRateHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetTradeHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetTradeHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetOptionSettlementHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetOptionSettlementHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetLiquidationHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetLiquidationHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetInterestRateHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetInterestRateHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetTransaction (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetTransaction", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetMargin (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetMargin", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostMarginWatch (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostMarginWatch", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostValidateInviteCode (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostValidateInviteCode", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetPoints (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetPoints", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetAllPoints (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetAllPoints", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetPointsLeaderboard (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetPointsLeaderboard", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetDescendantTree (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetDescendantTree", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetTreeRoots (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetTreeRoots", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetSwellPercentPoints (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetSwellPercentPoints", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetVaultAssets (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetVaultAssets", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetEtherfiEffectiveBalances (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetEtherfiEffectiveBalances", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetKelpEffectiveBalances (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetKelpEffectiveBalances", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetBridgeBalances (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetBridgeBalances", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetEthenaParticipants (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetEthenaParticipants", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetVaultShare (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetVaultShare", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetVaultStatistics (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetVaultStatistics", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetVaultBalances (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetVaultBalances", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostEstimateIntegratorPoints (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostEstimateIntegratorPoints", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostCreateSubaccountDebug (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostCreateSubaccountDebug", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostDepositDebug (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostDepositDebug", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostWithdrawDebug (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostWithdrawDebug", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostSendQuoteDebug (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostSendQuoteDebug", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostExecuteQuoteDebug (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostExecuteQuoteDebug", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetInviteCode (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetInviteCode", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostRegisterInvite (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostRegisterInvite", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetTime (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetTime", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetLiveIncidents (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetLiveIncidents", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetMakerPrograms (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetMakerPrograms", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PublicPostGetMakerProgramScores (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicPostGetMakerProgramScores", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetAccount (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetAccount", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostCreateSubaccount (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostCreateSubaccount", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetSubaccount (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetSubaccount", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetSubaccounts (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetSubaccounts", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetAllPortfolios (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetAllPortfolios", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostChangeSubaccountLabel (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostChangeSubaccountLabel", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetNotificationsv (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetNotificationsv", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostUpdateNotifications (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostUpdateNotifications", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostDeposit (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostDeposit", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostWithdraw (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostWithdraw", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostTransferErc20 (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostTransferErc20", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostTransferPosition (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostTransferPosition", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostTransferPositions (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostTransferPositions", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostOrder (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostOrder", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostReplace (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostReplace", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostOrderDebug (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostOrderDebug", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetOrder (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetOrder", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetOrders (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetOrders", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetOpenOrders (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetOpenOrders", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostCancel (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostCancel", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostCancelByLabel (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostCancelByLabel", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostCancelByNonce (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostCancelByNonce", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostCancelByInstrument (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostCancelByInstrument", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostCancelAll (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostCancelAll", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostCancelTriggerOrder (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostCancelTriggerOrder", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetOrderHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetOrderHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetTradeHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetTradeHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetDepositHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetDepositHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetWithdrawalHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetWithdrawalHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostSendRfq (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostSendRfq", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostCancelRfq (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostCancelRfq", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostCancelBatchRfqs (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostCancelBatchRfqs", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetRfqs (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetRfqs", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostPollRfqs (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostPollRfqs", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostSendQuote (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostSendQuote", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostCancelQuote (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostCancelQuote", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostCancelBatchQuotes (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostCancelBatchQuotes", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetQuotes (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetQuotes", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostPollQuotes (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostPollQuotes", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostExecuteQuote (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostExecuteQuote", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostRfqGetBestQuote (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostRfqGetBestQuote", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetMargin (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetMargin", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetCollaterals (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetCollaterals", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetPositions (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetPositions", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetOptionSettlementHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetOptionSettlementHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetSubaccountValueHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetSubaccountValueHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostExpiredAndCancelledHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostExpiredAndCancelledHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetFundingHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetFundingHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetInterestHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetInterestHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetErc20TransferHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetErc20TransferHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetLiquidationHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetLiquidationHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostLiquidate (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostLiquidate", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetLiquidatorHistory (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetLiquidatorHistory", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostSessionKeys (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostSessionKeys", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostEditSessionKey (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostEditSessionKey", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostRegisterScopedSessionKey (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostRegisterScopedSessionKey", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetMmpConfig (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetMmpConfig", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostSetMmpConfig (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostSetMmpConfig", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostResetMmp (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostResetMmp", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostSetCancelOnDisconnect (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostSetCancelOnDisconnect", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostGetInviteCode (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetInviteCode", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *derive) PrivatePostRegisterInvite (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostRegisterInvite", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}
