// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package coinbaseinternational

import ccxt "github.com/ccxt/ccxt/go/v4/ccxt"

func (this *coinbaseinternational) V1PublicGetAssets (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PublicGetAssets", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PublicGetAssetsAssets (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PublicGetAssetsAssets", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PublicGetAssetsAssetNetworks (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PublicGetAssetsAssetNetworks", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PublicGetInstruments (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PublicGetInstruments", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PublicGetInstrumentsInstrument (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PublicGetInstrumentsInstrument", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PublicGetInstrumentsInstrumentQuote (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PublicGetInstrumentsInstrumentQuote", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PublicGetInstrumentsInstrumentFunding (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PublicGetInstrumentsInstrumentFunding", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PublicGetInstrumentsInstrumentCandles (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PublicGetInstrumentsInstrumentCandles", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivateGetOrders (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivateGetOrders", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivateGetOrdersId (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivateGetOrdersId", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivateGetPortfolios (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivateGetPortfolios", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivateGetPortfoliosPortfolio (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivateGetPortfoliosPortfolio", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivateGetPortfoliosPortfolioDetail (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivateGetPortfoliosPortfolioDetail", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivateGetPortfoliosPortfolioSummary (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivateGetPortfoliosPortfolioSummary", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivateGetPortfoliosPortfolioBalances (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivateGetPortfoliosPortfolioBalances", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivateGetPortfoliosPortfolioBalancesAsset (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivateGetPortfoliosPortfolioBalancesAsset", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivateGetPortfoliosPortfolioPositions (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivateGetPortfoliosPortfolioPositions", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivateGetPortfoliosPortfolioPositionsInstrument (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivateGetPortfoliosPortfolioPositionsInstrument", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivateGetPortfoliosFills (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivateGetPortfoliosFills", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivateGetPortfoliosPortfolioFills (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivateGetPortfoliosPortfolioFills", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivateGetTransfers (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivateGetTransfers", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivateGetTransfersTransferUuid (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivateGetTransfersTransferUuid", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivatePostOrders (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivatePostOrders", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivatePostPortfolios (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivatePostPortfolios", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivatePostPortfoliosMargin (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivatePostPortfoliosMargin", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivatePostPortfoliosTransfer (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivatePostPortfoliosTransfer", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivatePostTransfersWithdraw (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivatePostTransfersWithdraw", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivatePostTransfersAddress (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivatePostTransfersAddress", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivatePostTransfersCreateCounterpartyId (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivatePostTransfersCreateCounterpartyId", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivatePostTransfersValidateCounterpartyId (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivatePostTransfersValidateCounterpartyId", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivatePostTransfersWithdrawCounterparty (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivatePostTransfersWithdrawCounterparty", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivatePutOrdersId (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivatePutOrdersId", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivatePutPortfoliosPortfolio (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivatePutPortfoliosPortfolio", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivateDeleteOrders (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivateDeleteOrders", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *coinbaseinternational) V1PrivateDeleteOrdersId (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v1PrivateDeleteOrdersId", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}
