package paymium

import "github.com/ccxt/ccxt/go/v4/ccxt"

type Paymium struct {
   *paymium
   Core *paymium
}

func NewPaymium(userConfig map[string]interface{}) Paymium {
   p := &paymium{}
   p.Init(userConfig)
   return Paymium{
       paymium: p,
       Core:  p,
   }
}

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


/**
 * @method
 * @name paymium#fetchBalance
 * @description query for balance and get the amount of funds available for trading or funds locked in orders
 * @see https://paymium.github.io/api-documentation/#tag/User/paths/~1user/get
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} a [balance structure]{@link https://docs.ccxt.com/#/?id=balance-structure}
 */
func (this *Paymium) FetchBalance(params ...interface{}) (ccxt.Balances, error) {
    res := <- this.Core.FetchBalance(params...)
    if ccxt.IsError(res) {
        return ccxt.Balances{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewBalances(res), nil
}
/**
 * @method
 * @name paymium#fetchOrderBook
 * @description fetches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
 * @see https://paymium.github.io/api-documentation/#tag/Public-data/paths/~1data~1%7Bcurrency%7D~1depth/get
 * @param {string} symbol unified symbol of the market to fetch the order book for
 * @param {int} [limit] the maximum amount of order book entries to return
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} A dictionary of [order book structures]{@link https://docs.ccxt.com/#/?id=order-book-structure} indexed by market symbols
 */
func (this *Paymium) FetchOrderBook(symbol string, options ...ccxt.FetchOrderBookOptions) (ccxt.OrderBook, error) {

    opts := ccxt.FetchOrderBookOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var limit interface{} = nil
    if opts.Limit != nil {
        limit = *opts.Limit
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.FetchOrderBook(symbol, limit, params)
    if ccxt.IsError(res) {
        return ccxt.OrderBook{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewOrderBook(res), nil
}
/**
 * @method
 * @name paymium#fetchTicker
 * @description fetches a price ticker, a statistical calculation with the information calculated over the past 24 hours for a specific market
 * @see https://paymium.github.io/api-documentation/#tag/Public-data/paths/~1data~1%7Bcurrency%7D~1ticker/get
 * @param {string} symbol unified symbol of the market to fetch the ticker for
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} a [ticker structure]{@link https://docs.ccxt.com/#/?id=ticker-structure}
 */
func (this *Paymium) FetchTicker(symbol string, options ...ccxt.FetchTickerOptions) (ccxt.Ticker, error) {

    opts := ccxt.FetchTickerOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.FetchTicker(symbol, params)
    if ccxt.IsError(res) {
        return ccxt.Ticker{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewTicker(res), nil
}
/**
 * @method
 * @name paymium#fetchTrades
 * @description get the list of most recent trades for a particular symbol
 * @see https://paymium.github.io/api-documentation/#tag/Public-data/paths/~1data~1%7Bcurrency%7D~1trades/get
 * @param {string} symbol unified symbol of the market to fetch trades for
 * @param {int} [since] timestamp in ms of the earliest trade to fetch
 * @param {int} [limit] the maximum amount of trades to fetch
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {ccxt.Trade[]} a list of [trade structures]{@link https://docs.ccxt.com/#/?id=public-trades}
 */
func (this *Paymium) FetchTrades(symbol string, options ...ccxt.FetchTradesOptions) ([]ccxt.Trade, error) {

    opts := ccxt.FetchTradesOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var since interface{} = nil
    if opts.Since != nil {
        since = *opts.Since
    }

    var limit interface{} = nil
    if opts.Limit != nil {
        limit = *opts.Limit
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.FetchTrades(symbol, since, limit, params)
    if ccxt.IsError(res) {
        return nil, ccxt.CreateReturnError(res)
    }
    return ccxt.NewTradeArray(res), nil
}
/**
 * @method
 * @name paymium#createDepositAddress
 * @description create a currency deposit address
 * @see https://paymium.github.io/api-documentation/#tag/User/paths/~1user~1addresses/post
 * @param {string} code unified currency code of the currency for the deposit address
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} an [address structure]{@link https://docs.ccxt.com/#/?id=address-structure}
 */
func (this *Paymium) CreateDepositAddress(code string, options ...ccxt.CreateDepositAddressOptions) (ccxt.DepositAddress, error) {

    opts := ccxt.CreateDepositAddressOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.CreateDepositAddress(code, params)
    if ccxt.IsError(res) {
        return ccxt.DepositAddress{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewDepositAddress(res), nil
}
/**
 * @method
 * @name paymium#fetchDepositAddress
 * @description fetch the deposit address for a currency associated with this account
 * @see https://paymium.github.io/api-documentation/#tag/User/paths/~1user~1addresses~1%7Baddress%7D/get
 * @param {string} code unified currency code
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} an [address structure]{@link https://docs.ccxt.com/#/?id=address-structure}
 */
func (this *Paymium) FetchDepositAddress(code string, options ...ccxt.FetchDepositAddressOptions) (ccxt.DepositAddress, error) {

    opts := ccxt.FetchDepositAddressOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.FetchDepositAddress(code, params)
    if ccxt.IsError(res) {
        return ccxt.DepositAddress{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewDepositAddress(res), nil
}
/**
 * @method
 * @name paymium#fetchDepositAddresses
 * @description fetch deposit addresses for multiple currencies and chain types
 * @see https://paymium.github.io/api-documentation/#tag/User/paths/~1user~1addresses/get
 * @param {string[]|undefined} codes list of unified currency codes, default is undefined
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} a list of [address structures]{@link https://docs.ccxt.com/#/?id=address-structure}
 */
func (this *Paymium) FetchDepositAddresses(options ...ccxt.FetchDepositAddressesOptions) ([]ccxt.DepositAddress, error) {

    opts := ccxt.FetchDepositAddressesOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var codes interface{} = nil
    if opts.Codes != nil {
        codes = *opts.Codes
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.FetchDepositAddresses(codes, params)
    if ccxt.IsError(res) {
        return nil, ccxt.CreateReturnError(res)
    }
    return ccxt.NewDepositAddressArray(res), nil
}
/**
 * @method
 * @name paymium#createOrder
 * @description create a trade order
 * @see https://paymium.github.io/api-documentation/#tag/ccxt.Order/paths/~1user~1orders/post
 * @param {string} symbol unified symbol of the market to create an order in
 * @param {string} type 'market' or 'limit'
 * @param {string} side 'buy' or 'sell'
 * @param {float} amount how much of currency you want to trade in units of base currency
 * @param {float} [price] the price at which the order is to be fulfilled, in units of the quote currency, ignored in market orders
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} an [order structure]{@link https://docs.ccxt.com/#/?id=order-structure}
 */
func (this *Paymium) CreateOrder(symbol string, typeVar string, side string, amount float64, options ...ccxt.CreateOrderOptions) (ccxt.Order, error) {

    opts := ccxt.CreateOrderOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var price interface{} = nil
    if opts.Price != nil {
        price = *opts.Price
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.CreateOrder(symbol, typeVar, side, amount, price, params)
    if ccxt.IsError(res) {
        return ccxt.Order{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewOrder(res), nil
}
/**
 * @method
 * @name paymium#cancelOrder
 * @description cancels an open order
 * @see https://paymium.github.io/api-documentation/#tag/ccxt.Order/paths/~1user~1orders~1%7Buuid%7D/delete
 * @see https://paymium.github.io/api-documentation/#tag/ccxt.Order/paths/~1user~1orders~1%7Buuid%7D~1cancel/delete
 * @param {string} id order id
 * @param {string} symbol not used by paymium cancelOrder ()
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} An [order structure]{@link https://docs.ccxt.com/#/?id=order-structure}
 */
func (this *Paymium) CancelOrder(id string, options ...ccxt.CancelOrderOptions) (ccxt.Order, error) {

    opts := ccxt.CancelOrderOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var symbol interface{} = nil
    if opts.Symbol != nil {
        symbol = *opts.Symbol
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.CancelOrder(id, symbol, params)
    if ccxt.IsError(res) {
        return ccxt.Order{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewOrder(res), nil
}
/**
 * @method
 * @name paymium#transfer
 * @description transfer currency internally between wallets on the same account
 * @see https://paymium.github.io/api-documentation/#tag/Transfer/paths/~1user~1email_transfers/post
 * @param {string} code unified currency code
 * @param {float} amount amount to transfer
 * @param {string} fromAccount account to transfer from
 * @param {string} toAccount account to transfer to
 * @param {object} [params] extra parameters specific to the exchange API endpoint
 * @returns {object} a [transfer structure]{@link https://docs.ccxt.com/#/?id=transfer-structure}
 */
func (this *Paymium) Transfer(code string, amount float64, fromAccount string, toAccount string, options ...ccxt.TransferOptions) (ccxt.TransferEntry, error) {

    opts := ccxt.TransferOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.Transfer(code, amount, fromAccount, toAccount, params)
    if ccxt.IsError(res) {
        return ccxt.TransferEntry{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewTransferEntry(res), nil
}