// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package mercado

import ccxt "github.com/ccxt/ccxt/go/v4/ccxt"

func (this *mercado) PublicGetCoins (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetCoins", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *mercado) PublicGetCoinOrderbook (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetCoinOrderbook", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *mercado) PublicGetCoinTicker (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetCoinTicker", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *mercado) PublicGetCoinTrades (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetCoinTrades", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *mercado) PublicGetCoinTradesFrom (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetCoinTradesFrom", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *mercado) PublicGetCoinTradesFromTo (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetCoinTradesFromTo", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *mercado) PublicGetCoinDaySummaryYearMonthDay (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("publicGetCoinDaySummaryYearMonthDay", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *mercado) PrivatePostCancelOrder (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostCancelOrder", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *mercado) PrivatePostGetAccountInfo (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetAccountInfo", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *mercado) PrivatePostGetOrder (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetOrder", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *mercado) PrivatePostGetWithdrawal (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostGetWithdrawal", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *mercado) PrivatePostListSystemMessages (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostListSystemMessages", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *mercado) PrivatePostListOrders (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostListOrders", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *mercado) PrivatePostListOrderbook (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostListOrderbook", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *mercado) PrivatePostPlaceBuyOrder (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostPlaceBuyOrder", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *mercado) PrivatePostPlaceSellOrder (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostPlaceSellOrder", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *mercado) PrivatePostPlaceMarketBuyOrder (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostPlaceMarketBuyOrder", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *mercado) PrivatePostPlaceMarketSellOrder (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostPlaceMarketSellOrder", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *mercado) PrivatePostWithdrawCoin (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("privatePostWithdrawCoin", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *mercado) V4PublicGetCoinCandle (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v4PublicGetCoinCandle", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}

func (this *mercado) V4PublicNetGetCandles (args ...interface{}) <-chan interface{} {
   parameters := ccxt.GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ccxt.ToString(r)
           }
       }()
       ch <- (<-this.CallEndpoint ("v4PublicNetGetCandles", parameters))
       ccxt.PanicOnError(ch)
   }()
   return ch
}
