package tradeogre

import "github.com/ccxt/ccxt/go/v4/ccxt"

type TradeogreWs struct {
   *tradeogreWs
   Core *tradeogreWs
}

func NewTradeogreWs(userConfig map[string]interface{}) TradeogreWs {
   p := &tradeogreWs{}
   p.Init(userConfig)
   return TradeogreWs{
       tradeogreWs: p,
       Core:  p,
   }
}

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


func (this *TradeogreWs) WatchOrderBook(symbol string, options ...ccxt.WatchOrderBookOptions) (ccxt.IOrderBook, error) {

    opts := ccxt.WatchOrderBookOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var limit interface{} = nil
    if opts.Limit != nil {
        limit = *opts.Limit
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.WatchOrderBook(symbol, limit, params)
    if ccxt.IsError(res) {
        return ccxt.IOrderBook{}, ccxt.CreateReturnError(res)
    }
    return ccxt.NewIOrderBook(res), nil
}
func (this *TradeogreWs) WatchTrades(symbol string, options ...ccxt.WatchTradesOptions) ([]ccxt.Trade, error) {

    opts := ccxt.WatchTradesOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var since interface{} = nil
    if opts.Since != nil {
        since = *opts.Since
    }

    var limit interface{} = nil
    if opts.Limit != nil {
        limit = *opts.Limit
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.WatchTrades(symbol, since, limit, params)
    if ccxt.IsError(res) {
        return nil, ccxt.CreateReturnError(res)
    }
    return ccxt.NewTradeArray(res), nil
}
func (this *TradeogreWs) WatchTradesForSymbols(symbols []string, options ...ccxt.WatchTradesForSymbolsOptions) ([]ccxt.Trade, error) {

    opts := ccxt.WatchTradesForSymbolsOptionsStruct{}

    for _, opt := range options {
        opt(&opts)
    }

    var since interface{} = nil
    if opts.Since != nil {
        since = *opts.Since
    }

    var limit interface{} = nil
    if opts.Limit != nil {
        limit = *opts.Limit
    }

    var params interface{} = nil
    if opts.Params != nil {
        params = *opts.Params
    }
    res := <- this.Core.WatchTradesForSymbols(symbols, since, limit, params)
    if ccxt.IsError(res) {
        return nil, ccxt.CreateReturnError(res)
    }
    return ccxt.NewTradeArray(res), nil
}